### PR TITLE
Added thermo groups and libraries for nitrogen and halogen species

### PR DESCRIPTION
**Pull request by davidfarinajr**
This PR adds new thermo libraries and improves RMG's ability to estimate thermochemistry using group additivity for CHON, CHOF, CHOBr, and CHOCl species.  The new thermo groups were derived by holding existing CHO groups fixed.  The new thermo groups were primarily derived from the new G4 thermo libraries added in this PR.

What has been added:

New thermo libraries:
- CHON_G4
- CHOF_G4
- CHOCl_G4
- CHOBr_G4

New thermo groups:
- group.py
- radical.py
- longDistanceInteraction_noncyclic.py 

This PR:
1) Does not change performance of CHO groups in estimating thermochemistry for a large test set of species in RMG's thermo libraries:
Current groups:
[CHO_enthalpy_parity_master.pdf](https://github.com/ReactionMechanismGenerator/RMG-database/files/5017906/CHO_enthalpy_parity_master.pdf)
PR groups:
[CHO_enthalpy_parity_new_groups.pdf](https://github.com/ReactionMechanismGenerator/RMG-database/files/5017907/CHO_enthalpy_parity_new_groups.pdf)
2) Improves performance of group additivity in estimating enthalpy for nitrogen-containing species in g4pm2 test set:
Current groups:
[G4MP2_nitrogen_parity_master_groups.pdf](https://github.com/ReactionMechanismGenerator/RMG-database/files/5017918/G4MP2_nitrogen_parity_master_groups.pdf)
PR groups:
[G4MP2_nitrogen_parity_new_groups.pdf](https://github.com/ReactionMechanismGenerator/RMG-database/files/5017920/G4MP2_nitrogen_parity_new_groups.pdf)
3) Adds thermo groups for halogens to make GAV thermo estimates of halogenates species on-par with CHO groups:
[halogens_vs_CHO_enthalpy_parity.pdf](https://github.com/ReactionMechanismGenerator/RMG-database/files/5017933/halogens_vs_CHO_enthalpy_parity.pdf)

### CODE REVIEW

**Comment by davidfarinajr** [comment]
oops, looks like we have an RMGpy related atomtype issue.  I'll also open a PR on RMGpy to fix this

**Comment by davidfarinajr** [comment]
Looks like the missing GAV test is failing.  I need to add a new test molecule with a missing group

**Review by mazeau — COMMENTED** [review]
Okay so yay the tests all pass! 
But it is pretty hard to review this code. This is a hunk of stuff. 
I think it might help if you posted an example input file or something using the new thermo to show that it works without errors, and that the results are expected.
There's also the glaring problem that rmg database tests don't test anything with nitrogen........

**Comment by rwest** [comment]
I've been thinking about ways to avoid the automatic reformatting of things you didn't actually edit. But I think I have a better idea. Might something like this work?

1. interactive rebase
2. pause to edit the commit where you rewrite the groups
3. load and save the _unedited_ groups so they are all reformatted
4. make a commit that is nothing but reformatting
5. now restore the file after your edits, and ensure it is also machine-formatted.
6. continue the rebase, so your last commit just shows actual edits and not the reformatting.

This will end up with a reformatted file, but there will now be two commits: one just formatting, and one with chemically meaningful changes that can be reviewed more easily.

**Comment by rwest** [comment]
Also, could you add a sentence or two of detail to the `longDesc` fields?  Perhaps customized for each group, saying which or how many species were used in training, but only if that's easy. Otherwise could be the same for each, saying which thermo libraries were used and what level of theory they were at.

**Pull request closed without merging**
