### PR TITLE
added "heavy halogen interaction" long distance thermo group

### PR DESCRIPTION
**Pull request by davidfarinajr**
Our current GAVs overestimate stability (underestimate H298) of "heavily fluorinated" molecules such as C5F12, C6F14, and C7F16.  To correct this, I added a new load distance interaction group `CsF2-CsF2-CsF2` with an H298 correction of +2.5 kcal/mol to account to improve the thermo estimated of heavily halogenated mols.

### CODE REVIEW

**Review by ChrisBNEU — APPROVED** [review]
Looks fine to me. Were there similar problems for long range interactions in other halogenated compounds? Just curious.  I am assuming the electronegativity of fluorine makes it special compared to the others.

**Comment by davidfarinajr** [comment]
I also added a cis C(hal)3-C=C-C(hal3) correction here https://github.com/ReactionMechanismGenerator/RMG-database/pull/541/commits/c40af10768ba3474277ebfe6b964d54496493b10

Screen Shot 2021-11-15 at 4 02 30 PM

**Comment by davidfarinajr** [comment]
> Looks fine to me. Were there similar problems for long range interactions in other halogenated compounds? Just curious. I am assuming the electronegativity of fluorine makes it special compared to the others.

Yes, similar problems with other halogens.  They are harder to account for in GAV 2D graph scheme because they may be many neighbors away in graph, but the halogens are close in 3D

**Review by mazeau — APPROVED** [review]
this looks fine. all tests pass. I can't imagine what this would mess up

**Pull request merged**
