### PR TITLE
New fam drawings

### PR DESCRIPTION
**Pull request by alongd**
Added family drawings for
- 2+2_cycloaddition_CS
- Cyclic_Thioether_Formation
- Singlet_Val6_to_triplet

and modified arrow in 1,2-Birad_to_alkene

addresses #244 

@mliu49 , I'm new to ChemDraw, let me know if you'd like to see any changes.

### CODE REVIEW

**Comment by mliu49** [comment]
Thanks @alongd! I realized that I actually had uncommitted changes to the documents (updates following Zach's work), so I added a commit for that. I also combined all of the drawings into a single document to make it easier to work with and updated the pdf.

**Comment by mliu49** [comment]
@mjohnson541, could you check the pdf for any errors and merge?

**Comment by alongd** [comment]
Thanks. I'm not in front of a Windows machine, @mliu49, could you fix my typo?

**Comment by mliu49** [comment]
Should be fixed. I can squash and rebase when you think it's ok.

**Pull request merged**
