### PR TITLE
Aromatic Training Reactions for Non-R-Addition Families

### PR DESCRIPTION
**Pull request by zjburas**
Added kinetic/forbidden groups and training reactions for aromatic reactions in #222 that fall under non-R-addition families (i.e., not R_Addition_MultipleBond, which is covered by #218 , and not Intra_R_Add_Exo/Endocyclic, which @mliu49 is figuring out what to do with). Most of the changes are to the intra_H_migration family, with some changes to other families such as R_recombination, Intra_ene and H_abs. 

Also, added 2 new reaction families:

**Intra_R_Add_Exo_Scission**
image

**1,2_ShiftC**
image

I still have to actually add the training reactions, which will be done by tomorrow. Also, this PR partially takes the place of #207 .

### CODE REVIEW

**Comment by zjburas** [comment]
Alright, all training reactions have been added. Here is the breakdown according to reaction family:

- intra_H_migration: 47 training reactions
- H_abstraction: 12
- R_recombination: 15
- Intra_ene: 10
- 6_membered_central_C-C_shift: 4
- 1,4-cyclic_birad_scission: 2
- Intra_Disproportionation: 2

This PR is ready for review.

**Comment by laitcl** [comment]
All appropriate changes are made from my end.

**Comment by zjburas** [comment]
Thanks a lot @laitcl . Maybe @jimchu10 can resolve the conflict in rmg_families.pdf?

**Comment by jimchu10** [comment]
@zjburas  Sure, I will change rmg_families.pdf

**Comment by mliu49** [comment]
I went ahead and fixed the conflict with the reaction family drawings, since I created the conflict by merging the files together.

**Comment by mliu49** [comment]
RMG-tests shows significant changes as a result of this branch. While this is not unexpected, I'm not sure how to ensure that these are acceptable differences.

There are increases in time and memory across the board, but they are all due to additional species and reactions being found. The detailed differences can be found in the results.log file.

example|time benchmark|time new|memory benchmark|memory new
---|---|---|---|---
eg1|00:00:03:33|00:00:04:55|466.48|505.65
eg3|00:00:07:42|00:00:09:46|417.46|456.92
eg5|00:00:02:25|00:00:03:37|381.26|406.18
eg6|00:00:01:44|00:00:02:14|372.75|422.68
eg7|00:00:01:25|00:00:01:47|365.22|397.71
NC|00:00:02:29|00:00:02:47|379.93|400.95
solvent_hexane|00:00:01:48|00:00:02:08|361.53|393.95
MCH|00:00:05:38|00:00:05:46|806.90|879.84

[results.log](https://github.com/ReactionMechanismGenerator/RMG-database/files/1742559/results.log)

**Comment by zjburas** [comment]
I've given a quick read-through of the RMG-tests results to check for anything suspicious. Here's what I've come across.

**eg1:** 
The following reaction has significantly different kinetics because of a new training reaction (I'm guessing that @laitcl added the training reaction). Perhaps this reaction is somehow the central cause of all subsequent changes to the mechanism?
[CH2]CC=C(29) <=> [CH2]C=CC(58)
Kinetics: Arrhenius(A=(6.18e+09,'s^-1'), n=1.22, Ea=(47.8,'kcal/mol'), T0=(1,'K'), comment="""Exact match found for rate rule [R2H_S;C_rad_out_H/OneDe;Cs_H_out_2H]
Kinetics: Arrhenius(A=(1.72e+06,'s^-1'), n=1.99, Ea=(27.2,'kcal/mol'), T0=(1,'K'), comment="""Matched reaction 85 C:CC[CH2] <=> C:C[CH]C in intra_H_migration/training
kinetics: Exact match found for rate rule [R2H_S;C_rad_out_H/OneDe;Cs_H_out_2H]
kinetics: Matched reaction 85 C:CC[CH2] <=> C:C[CH]C in intra_H_migration/training

CH3 varied by more than 0.05 on average

**eg3**
Again, the following core reaction has significantly different kinetics due to a new training reaction that's an exact match:
[CH2]CCCCCCC(14) <=> C[CH]CCCCCC(13)	
Kinetics: Arrhenius(A=(2.43e+09,'s^-1'), n=1.32, Ea=(40.3,'kcal/mol'), T0=(1,'K'), comment="""Exact match found for rate rule [R2H_S;C_rad_out_H/NonDeC;Cs_H_out_2H]
Kinetics: Arrhenius(A=(1062,'s^-1'), n=1.81, Ea=(13.2,'kcal/mol'), T0=(1,'K'), comment="""Matched reaction 117 CCCCCCC[CH2]-2 <=> C[CH]CCCCCC in intra_H_migration/training
kinetics: Exact match found for rate rule [R2H_S;C_rad_out_H/NonDeC;Cs_H_out_2H]
kinetics: Matched reaction 117 CCCCCCC[CH2]-2 <=> C[CH]CCCCCC in intra_H_migration/training

Other similar intra_H_migration reactions also have different kinetics, although the root cause is not as clear because estimate templates were used. Presumably new training reactions such as 117 above are the root cause of the change in kinetics.

**eg5**
CCCCCCC varied by more than 0.050 on average 

This mechanism has a lot of P-dep reactions, so it's difficult to trace back the origin of the discrepancy.

**eg6**
CC varied by more than 0.050 on average 

This mechanism also  has a lot of P-dep reactions, so it's difficult to trace back the origin of the discrepancy.

**eg7**
Nothing suspicious to report

**NC**
CN varied by more than 0.200 on average 

**solvent_hexane**
A lot of intra_H_migration and Birad_R_Recombination kinetics are different. Again, the intra_H_migration is probably due to @laitcl 's new training reactions, but Birad_R_Recombination I'm not sure about since this PR didn't touch that family.

**MCH**
Following core reaction has significantly different kinetics due to a new training reaction (added by @jimchu10 from the 2012_Matsugi_C3H3_C7H7_highP library):
 H(3) + [CH2]C=CCC[CH2](151) <=> [CH2]CCCC=C(84)	
Kinetics: Arrhenius(A=(2.92e+13,'cm^3/(mol*s)'), n=0.18, Ea=(0.124,'kcal/mol'), T0=(1,'K'), comment="""Estimated using template [C_rad/H/OneDeC;H_rad] for rate rule [C_rad/H/CdCs;H_rad]
Kinetics: Arrhenius(A=(1.46817e+13,'cm^3/(mol*s)'), n=-0.055, Ea=(7.745,'kcal/mol'), T0=(1,'K'), comment="""From training reaction 45 for rate rule C_rad/H/CdCs;H_rad
kinetics: Estimated using template [C_rad/H/OneDeC;H_rad] for rate rule [C_rad/H/CdCs;H_rad]
kinetics: From training reaction 45 for rate rule C_rad/H/CdCs;H_rad

There are a lot (~150) of non-overlapping reactions between the benchmark and test mechanisms. 

CC1CCCCC1 varied by more than 0.050 

**Conclusions**
Almost all of the changes to kinetics can be explained by new training reactions. Explaining the missing/new core reactions would require more investigation. Perhaps it would be most helpful to visualize how much the simulated profiles highlighted above are in disagreement?

**Comment by mliu49** [comment]
Thanks for looking into this @zjburas! I'll take a look at the simulation profiles to see how much they differ.

**Pull request merged**
