### PR TITLE
added thermo groups for heteropolycyclics containing one or two oxygens

### PR DESCRIPTION
**Pull request by yunsiechung**
4 new thermo groups are added for heteropolycyclics containing one or two oxygens. These thermo corrections are calculated using the CBS-QB3 method.

s3_5_6_ane_hetero_O and s3_5_6_ane_hetero_OO are added as children of s3_5_6_ane.
s4_6_6_ane_hetero_O and s4_6_6_ane_hetero_OO are added as children of s4_6_6_ane.

### CODE REVIEW

**Comment by yunsiechung** [comment]
I realized that I forgot to apply bond energy corrections to one of the fused heterocyclic groups, so I'm recalculating the corrections.

**Comment by yunsiechung** [comment]
I fixed the values by applying the bond energy corrections to my fused heterocyclic groups calculated using the CBS-QB3 job.

**Comment by yunsiechung** [comment]
@KEHANG Do you mind reviewing this and see what's causing the check failure? I cannot see the job log for the test. It passed the RMG-database test when I ran it on my laptop.

**Comment by KEHANG** [comment]
@yunsiechung sometimes Travis has random build failure, you can restart the build on the upper right corner (that's what I did) usually will pass in a second trial if that's the case.

**Pull request closed without merging**
