### PR TITLE
More Intra_R_Add_Endocyclic training rates

### PR DESCRIPTION
**Pull request by mliu49**
I got assigned to add these rates a while ago but never got around to pushing them...

These are rates computed at the CBS-QB3 level of theory, from a 2015 paper by Wang, Villano, and Dean (http://pubs.acs.org/doi/abs/10.1021/jp511017z).

I added some nodes to the tree to prevent some of the rates from falling to the same node. However, I don't know if they way I added them are computationally or chemically optimal. Someone else should definitely review them before merging.

### CODE REVIEW

**Comment by nyee** [comment]
@mliu49 Can you rebase and re-push this? I quickly tried it with all new tests and it seems to pass everything, so I don't forsee any problems.

**Comment by nyee** [comment]
Might be a nit-pick, but I think we should have different names on the training reactions. It just worries me that you use a ', in the name, which can be used to start a string in python code. I suggest a mixture of SMILES and HBI notation

_ for double bond is fine since we obviously can't use =
J for radical
() for branch

So C2C_CCC' would become C(C)C_CCCJ. I feel like this is more immediately readable to the average user. 

If you think its not worth the time, you might be right...so I'm okay if you merge as-is also.

**Comment by mliu49** [comment]
I can make those changes. I was trying to mimic the notation in the paper, which used = for double bonds and dots for radicals.

**Comment by mliu49** [comment]
I changed the species labels. I think it should be ready for merging.

**Pull request merged**
