### PR TITLE
AEC BAC for ωB97X-D3/def2-TZVP and B97-D3/def2-mSVP

### PR DESCRIPTION
**Pull request by kspieks**
This PR adds frequency scaling factors, AEC, and BAC for two levels of theory: `ωB97X-D3/def2-TZVP` and `B97-D3/def2-mSVP`. All calculations were run with QChem 5.3

Frequency scaling factors were computed using ARC.

AECs were determined by running sp calculations of the 16 small molecules from the reference database. The experimental geometries were used i.e. no optimization was performed. 

BACs were determined by running opt + freq jobs in QChem using ARC. The reference database previously had stored the optimized geometries from `ωB97M-V/def2-TZVPD`; these geometries were used as the initial guess. Rotors were not considered. A few molecules failed during QM by either not converging during geometry optimization or yielding a negative frequency despite being a stable species, not a TS; these molecules were omitted and the remaining 400+ molecules were used for BACs fitting. 

For `ωB97X-D3/def2-TZVP`:

- RMSE/MAE before fitting: 6.81/5.13 kcal/mol
- RMSE/MAE after fitting: 2.21/1.33 kcal/mol

[1_wb97xd3_def2tzvp_errors.pdf](https://github.com/ReactionMechanismGenerator/RMG-database/files/6137363/1_wb97xd3_def2tzvp_errors.pdf)

For `B97-D3/def2-mSVP`: 

- RMSE/MAE before fitting: 27.85/21.78 kcal/mol
- RMSE/MAE after fitting: 6.58/3.16 kcal/mol

[1_b97d3_def2msvp_errors.pdf](https://github.com/ReactionMechanismGenerator/RMG-database/files/6137365/1_b97d3_def2msvp_errors.pdf)

### CODE REVIEW

**Comment by alongd** [comment]
@kspieks, could you make a twin RMG-Py PR to update [the model chemistry table](http://reactionmechanismgenerator.github.io/RMG-Py/users/arkane/input.html#model-chemistry) in the docs?

**Comment by kspieks** [comment]
@alongd Will do! Thanks for reminding me

**Review by xiaoruiDong — COMMENTED** [review]
Thanks, Kevin! This is well documented. I guess it is acceptable to have those parameters fitted without rotor and non-converged species. Just a minor comment that ARC can sometimes give a wrong symmetry number and stereoisomer number. You may need to have a double check on those numbers.

**Comment by kspieks** [comment]
> Thanks, Kevin! This is well documented. I guess it is acceptable to have those parameters fitted without rotor and non-converged species.

@xiaoruiDong Does this PR look ready to be merged? 

I’m unsure why the continuous integration of rmg-tests are failing, but it seems like that has failed for many recent PRs. I can add it as a [hackathon topic](https://github.com/ReactionMechanismGenerator/RMG-Py/discussions/2087) for us to look into.

Regarding conformers, my understanding was that the experimental geometry from CCCBDB was used as the initial guess for ωb97mv optimization (whose converged geometry was the initial guess for my calculations). It’s possible Colin did a conformer search with ARC for these species, but I’m unsure where the log files are so I can’t check for sure. Looks like other PRs (#412) for adding BACs also did not consider rotors (or the PR (#417) doesn't comment on it).

**Comment by xiaoruiDong** [comment]
@kspieks Thanks. This PR looks good. Can you also update the reference database yamls with D97-B3/def2-mSVP energies? Once they are updated, please rebase the PR, and I will merge it into the master branch. Thanks!

**Comment by kspieks** [comment]
> @kspieks Thanks. This PR looks good. Can you also update the reference database yamls with D97-B3/def2-mSVP energies? Once they are updated, please rebase the PR, and I will merge it into the master branch. Thanks!

Thanks for reviewing! I updated the reference database with b97d3/def2-msvp data :)

**Comment by kspieks** [comment]
FYI: all log files and Arkane outputs related to these jobs have been copied to my account on our new greencloud sever at `/volume1/home/users/kspieker/AEC_BAC_calculations`

**Pull request merged**
