### PR TITLE
Primary thermo library additions

### PR DESCRIPTION
**Pull request by davidfarinajr**
This PRs added some key species to primaryThermoLibrary

#### CO, OCCCO (because GAV is poor https://github.com/ReactionMechanismGenerator/RMG-database/issues/476)

simultaneous with https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2123

### CODE REVIEW

**Comment by davidfarinajr** [comment]
```
A general test for a PDep job in Arkane ... ok
1755

1756
======================================================================
1757
FAIL: test that the right number of reactions are in output network
1758
----------------------------------------------------------------------
1759
Traceback (most recent call last):
1760
  File "/home/runner/work/RMG-database/RMG-Py/arkane/explorerTest.py", line 81, in test_reactions
1761
    self.assertEqual(len(self.explorer_job.networks[0].path_reactions), 6)
1762
AssertionError: 7 != 6
1763

1764
----------------------------------------------------------------------
1765
Ran 30 tests in 877.222s
1766

1767
FAILED (failures=1)
1768
make: *** [Makefile:78: test-functional] Error 1
1769
Error: Process completed with exit code 2.
```
🤔
Not sure why this is failing

**Comment by rwest** [comment]
> Not sure why this is failing

It's trying to run https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/arkane/data/methoxy_explore.py
Presumably the thermo of one of the intermediates has changed.
Hopefully for the better :)
it has `energy_tol=4.5e1,` (I'm not sure what units). Tweaking that may change something 🤷 
Someone like @alongd would know better.

Again, check the [rmg-tests logs](https://travis-ci.org/github/ReactionMechanismGenerator/RMG-tests/builds/769980242) for any significant changes, and justify them here as being improvements.

**Comment by davidfarinajr** [comment]
```
Non-identical thermo!
2915original:	[C-]#[O+]
2916tested:	CO
2917Hf(300K)  |S(300K)   |Cp(300K)  |Cp(400K)  |Cp(500K)  |Cp(600K)  |Cp(800K)  |Cp(1000K) |Cp(1500K) 
2918     70.71|     32.69|      8.89|      9.07|      9.30|      9.69|     10.90|     12.05|     12.92
2919    -29.71|     40.97|      6.95|      7.02|      7.13|      7.27|      7.57|      7.86|      8.35
2920thermo: Thermo group additivity estimation: group(O2s-CsCs) + group(CsJ2_singlet-CsH) + Solvation correction with pentane as solvent and solute estimated
2921thermo: Thermo library corrected for liquid phase: primaryThermoLibrary + Solvation correction with pentane as solvent and solute estimated using
```
because we added CO to primaryThermoLibrary with PR, so thermo is much better

**Comment by rwest** [comment]
You could perhaps change the unit test so it asserts we now make 7 path reactions instead of 6?  (and then request Alon as a reviewer)

**Comment by davidfarinajr** [comment]
```
Non-identical kinetics!
2881original:
2882rxn: CH2(T)(7) + [CH3](4) <=> C[CH2](5)		origin: Birad_R_Recombination
2883tested:
2884rxn: CH2(T)(7) + [CH3](4) <=> C[CH2](5)		origin: Birad_R_Recombination
2885k(1bar)|300K   |400K   |500K   |600K   |800K   |1000K  |1500K  |2000K  
2886
2887k(T):  |  -3.86|  -1.46|  -0.03|   0.91|   2.07|   2.76|   3.64|   4.06
2888k(T):  |   7.06|   7.13|   7.18|   7.22|   7.29|   7.35|   7.45|   7.52
```
because we added `NO` and `NO2` to primaryThermoLibrary and they are both in a reverse training reaction in Birad_R_Recombination 

```
entry(
    index = 2,
    label = "NO2_p <=> NO + O",
    degeneracy = 1.0,
    kinetics = Arrhenius(
        A = (3.98e+14, 's^-1'),
        n = 0,
        Ea = (71700, 'cal/mol'),
        T0 = (1, 'K'),
        Tmin = (1350, 'K'),
        Tmax = (2100, 'K'),
    ),
    rank = 1,
    shortDesc = u"""Training reaction from kinetics library: primarySulfurLibrary""",
    longDesc = 
u"""
T range: 1350-2100 K
M. Rohrig, E.L. Petersen, D.F. Davidson, R.K. Hanson, Int. J. Chem. Kin., 1997, 29(7), 483-493, doi: 10.1002/(SICI)1097-4601(1997)29:7<483::AID-KIN2>3.0.CO;2-Q
Shock tube measurement
Originally a Troe expression was given, only k_inf is taken here
""",
)
```

**Comment by davidfarinajr** [comment]
just changed unit test on https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2123 branch

**Comment by davidfarinajr** [comment]
The reverse training reaction thermo was previously discussed here https://github.com/ReactionMechanismGenerator/RMG-database/issues/461

**Review by rwest — APPROVED** [review]
Thanks for tracking down and explaining those changes in the rmg-tests logs.

I tracked down some of the original sources (took some lucky guesses and forensics) and updated the metadata in https://github.com/ReactionMechanismGenerator/RMG-database/pull/478/commits/ec11833741c6e28ac00c345cc6b88c69c308f488
Some of the reference values are derived in 1971 on the basis of data from 1950.
We might be able to do better. But this is an improvement on a group additive guess,
so I approve.

One (rhetorical?) question might be how extensive should this primary thermo library become?

Anyway, happy to approve.

**Pull request merged**
