### PR TITLE
Added CHON_G4 thermo library, nitrogen group additivity values and radical groups

### PR DESCRIPTION
**Pull request by davidfarinajr**
This PR adds a bunch of new nitrogen data:
- Added a thermo library of >2000 randomly generate CHON species calculated with G4 method with 1D hindered rotors
- Added about 200 nitrogen-containing group additivity values.  Groups were derived from all stable, non-cyclic CHON species with 3 or more heavy atoms in RMG thermo libraries including new CHON_G4 library (about ~1500 spcs)
- Added about 75 nitrogen-containing radical groups. Radical groups were derived similarly: from all radical, non-cyclic CHON species with 3 or more heavy atoms in RMG thermo libraries including new CHON_G4 library. Only the radicals for which the saturated complement is also in libraries were used in training.

Figure below shows the performance of new groups vs current groups for test set of 7545 non-cylic CHON species from G4MP2 data set (https://doi.org/10.1039/C9SC02834J)

Screen Shot 2020-04-16 at 6 53 36 PM

### CODE REVIEW

**Comment by davidfarinajr** [comment]
```
FAIL: Test identifying a missing GAV group
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/ReactionMechanismGenerator/RMG-Py/rmgpy/data/thermoTest.py", line 615, in test_identifying_missing_group
    self.assertIn('missing(N3s-CbCbCs)', thermo_gav.comment)
AssertionError: 'missing(N3s-CbCbCs)' not found in 'Thermo group additivity estimation:
group(N3s-CsCsCs) + group(N3s-CCC) + group(Cs-CsCsHH) + group(Cs-N3sCsHH) +
 group(Cs-N3sCsHH) + group(Cs-CbCsHH) + group(Cs-CbCsHH) + group(Cs-N3sHHH) +
 group(Cs-N3sHHH) + group(Cb-Cs) + group(Cb-Cs) + group(Cb-N3s) + group(Cb-N3s) +
 group(Cb-H) + group(Cb-H) + group(Cb-H) + group(Cb-H) + group(Cb-H) + group(Cb-H) +
 group(Cb-H) + group(Cb-H) + polycyclic(s2_6_7_ben) + polycyclic(s2_6_7_ben) -
 ring(Cycloheptane)
```


This is the database error.  However, I do not see this group `N3s-CbCbCs` in the master database.  Is this a typo in the unit test maybe?

**Comment by alongd** [comment]
note that the test is looking for `missing(N3s-CbCbCs)`, i.e., we know this group is missing, and we look for a proper metadata to indicate that

**Comment by davidfarinajr** [comment]
I am having trouble "cleaning up" my commit history for this PR.  It's a mess since I loaded the database into memory, added and fit the groups, then saved it.  Any advice or suggestions about how to make prettier commits so this is easier to review?

**Comment by alongd** [comment]
@davidfarinajr, I see the commits are organized by `group.py`, `radical.py`, and a library. Looks like the group and radical modifications replaced the content altogether. By "cleaning up the commit history", do you mean you'd like the diff to show how each group changed? If it's important, I'd run a script that sorts the new file by the old one, and append all new groups at the end. The question is whether that's important: would we as reviewers or future users like to see how each group changed? I'm not sure that's significant. @mjohnson541, could you comment?

**Comment by davidfarinajr** [comment]
Yes, I mean the diff.  The non-nitrogen groups (C,H,O,S) didn't change, although its hard to tell from the commits because it replaced the entire file.  I did, however, remove some existing nitrogen super groups as they were incompatible with my new groups.

**Comment by davidfarinajr** [comment]
Do we have such a script?  Perhaps one was used when the sulfur groups were added?  It would be nice to have one for this PR and moving forward, as I will be adding a lot of new halogen (F,Cl,Br) thermo groups.

**Comment by alongd** [comment]
I'm not aware of an existing script.
@mjohnson541, what's your take on this?

**Comment by mjohnson541** [comment]
It's very important in git history for us to be able to see when something got changed and why it got changed, that's why it's important for commits to be clean and commit messages clear. Furthermore, if we can't tell what changed we can't properly review changes. This needs to be built on top of the original files so it makes sense in the history.

**Comment by rwest** [comment]
Please could you also add to the shortDesc and especially the longDesc of the CHON_G4 library, explaining what it contains, where it came from, how it was calculated, and when it should be used?

**Comment by davidfarinajr** [comment]
This PR has been replaced by https://github.com/ReactionMechanismGenerator/RMG-database/pull/414

**Pull request closed without merging**
