### PR TITLE
Put reaction family drawings in each family directory

### PR DESCRIPTION
**Pull request by mliu49**
This PR addresses the suggestion in #316 to put family drawings in each individual family directory.

What has been done:
- Each drawing from the existing ChemDraw document was copied into a separate document
- Each drawing was also exported in .eps format
- A Python script was written to compile the drawings into a single file via LaTeX

What needs to be done:
- Drawings are missing for a number of families. Families without images are also noted in `rmg_reaction_families.pdf`.
- Decide what other image formats are desirable. Conversion from .eps should be trivial with tools like ImageMagick, so the main considerations would be user needs and file size.

### CODE REVIEW

**Comment by mliu49** [comment]
To be more specific, the families which are missing images are
- 1,2_NH3_elimination, 1,3_NH3_elimination @alongd 
- All surface families @rwest @mazeau 

Could you please create these drawings and push them to this branch?

**Comment by rwest** [comment]
I would suggest png, for easy viewing, previewing on github, and for use in 
https://rmg.mit.edu/database/kinetics/families/
And somewhere, some instructions on how and when to run the conversion. 
And should this be part of a conda build or travis test?

**Comment by mliu49** [comment]
Any updates on the family drawings? Let me know if you need me to make the drawings instead.

**Comment by alongd** [comment]
I haven't gotten around to install ChemDraw yet. It would be helpful if you could make them instead :). Thanks!

**Comment by rwest** [comment]
@mazeau or @kblondal do you have chemdraw files from our paper(s) you could use for this?

**Comment by kblondal** [comment]
I have some chemdraw files from when I made Pt adsorbate thermo database pictures.

**Comment by alongd** [comment]
Thanks @mliu49!

**Comment by mliu49** [comment]
I would like to get this in soon for the release.

@mazeau @kblondal Are the chemdraw files you have of the labeled templates? If so, could you send them to me (via email or slack), and I can make any formatting changes if necessary. Otherwise, I could make the drawings myself, but interpreting the reaction recipes and templates actually takes a surprising amount of time.

**Comment by mazeau** [comment]
@mliu49 I don't have any in chemdraw format, we do have the labeled templates in the long description in groups.py.  Do you want chemdraw files in addition to that as well?

**Comment by rwest** [comment]
We did our best with ascii-art (in the groups.py files), so it might not be tooooo hard.

**Comment by mliu49** [comment]
Ah, I see now. That's very helpful, and should be good enough to work from. Thanks!

**Comment by kblondal** [comment]
I don't know if it will save time creating the reaction template figures, but let me know if I should send the adsorbate chemdraw files I have @mliu49

**Comment by mliu49** [comment]
I finished drawing all of the surface families. The ascii art was very helpful! Please take a look and let me know if they look alright. [Link to pdf](https://github.com/ReactionMechanismGenerator/RMG-database/blob/split_fam_draw/families/rmg_reaction_families.pdf)

I finalized the script and added a function to convert the eps files to pngs, located in `families/images`.

Comments or suggestions are welcome.

**Comment by mazeau** [comment]
I might be a bit confused, but the surface abstraction doesn't quite match the figures, but everything else looks good!

**Comment by mliu49** [comment]
Thanks for catching that! I'll fix it tomorrow.

**Comment by mliu49** [comment]
Any other comments before merging?

**Comment by rwest** [comment]
Looked good to me last night. Thanks for doing this

**Pull request merged**
