### PR TITLE
Aromatic libraries

### PR DESCRIPTION
**Pull request by zjburas**
Adding four aromatic libraries from literature:
1. Fascella
2. Kislov
3. Chernov
4. Narayanaswamy

### CODE REVIEW

**Comment by PengZhang13** [comment]
Looks like we have crazy thermo for CH2HCO in Chernov library, as shown [here](http://rmg.mit.edu/database/thermo/molecule/multiplicity%202%0A1%20C%20u1%20p0%20c0%20%7B2,S%7D%20%7B3,S%7D%20%7B4,S%7D%0A2%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B5,S%7D%20%7B6,D%7D%0A3%20H%20u0%20p0%20c0%20%7B1,S%7D%0A4%20H%20u0%20p0%20c0%20%7B1,S%7D%0A5%20H%20u0%20p0%20c0%20%7B2,S%7D%0A6%20O%20u0%20p2%20c0%20%7B2,D%7D%0A). 
All the libraries agree well with each other except Chernov library.
I checked the NASA polynomial. It's same to the source paper. So it's not because our typo. 
Since we already have good thermo for this species in other libraries, maybe we could just delete it from this library? Not sure if it affects any projects....

**Comment by zjburas** [comment]
@PengZhang13 , yes, that species can be deleted from Chernov. In fact, the main purpose of both the Chernov and Narayanaswamy libraries was to provide estimates for aromatic thermo and kinetics, so really all non-aromatic species and reactions could be removed from these libraries without defeating their original purpose. I already have "aromatics only" versions of these libraries that I could push to the master if there is interest in that.

**Comment by PengZhang13** [comment]
@zjburas I see. Thanks. I checked the thermo for other small molecules in Chernov. They looked reasonable for me. So maybe we could just delete the crazy one (CH2HCO) and keep the others. Or you could push the 'aromatics only' versions if you don't believe their estimation for non-aromatic molecules. The point is I think we need to make sure the data in the libraries are reasonable, to avoid any potential trouble caused by unintentional usage. In my case, I'm trying to convert a kinetics library to a chemkin file using a script in RMG-database/scripts. The script doesn't specify any specific thermo libraries for the conversion. So in the exported chemkin file, the thermo for CH2HCO was taken from Chernov, which finally caused weird behavior in the subsequent simulation. That's how I find out the thermo for this species is not reasonable.

**Comment by zjburas** [comment]
@PengZhang13 ok. We will have to update both the Chernov and Narayanaswamy aromatic libraries soon anyway to make all of the aromatic have benzene bonds according to @mliu49 , so maybe at that time we can decide if we want to make any other changes to them, i.e., delete all non-aromatic containing reactions and species. Chernov certainly has some questionable small molecule kinetics (e.g., C2H6 = C2H4 + H2) that are probably not valuable to keep, especially since we have much better libraries for these types of reactions like FFCM.

**Pull request merged**
