### PR TITLE
Refit Intra R Add Endo/Exocyclic Rate Rules

### PR DESCRIPTION
**Pull request by kspieks**
This PR adds 1 training reaction to each of the `Intra_R_Add_Endocyclic` and `Intra_R_Add_Exocyclic` reaction families and also refits the rate rules. All calculations were done at `CCSD(T)-F12a/cc-pVDZ-F12//ωB97X-D3/def2-TZVP` and include conformer searches and 1D rotor scans. The notebooks for refitting the rate rules as well as a slide deck that summarizes the improved rate estimate for these reactions is included in the zip file below.

The training reaction added to `Intra_R_Add_Exocyclic` brings substantial improvements. Previously, the rate rules gave an estimate for k(T=673K) that was over 1000x smaller than the actual rate calculated from TST.

The training reaction added to `Intra_R_Add_Endocyclic` brings minor improvements. Previously, this training reaction, which just came from group additivity, gave an estimate for k(T=673K) that was ~5x smaller than the actual rate calculated from TST. Note that since the product for this training reaction is chiral, the A-factor had to be multiplied by 2 since the reactant can attack itself from either the top or the bottom (both options are possible and equally likely). 

Hopefully these new training reactions and rate rules improve people's mechanisms :)
[20220321.zip](https://github.com/ReactionMechanismGenerator/RMG-database/files/8319961/20220321.zip)

### CODE REVIEW

**Review by lily90502 — COMMENTED** [review]
This looks good to me

**Comment by kspieks** [comment]
For completeness, I actually refit these reaction families when rebasing and pushing using a better list of thermo libraries. The list I used is
```
thermo_libraries = [
                'ENI_1dHR', 'Spiekermann_refining_elementary_reactions', 
                'Klippenstein_Glarborg2016', 'BurkeH2O2', 'thermo_DFT_CCSDTF12_BAC', 'DFT_QCI_thermo',
                'primaryThermoLibrary', 'primaryNS', 'NitrogenCurran', 'NOx2018', 'FFCM1(-)',
                'SulfurLibrary', 'SulfurGlarborgH2S', 'SABIC_aromatics',
            ],
```

This is the same lists that are given by default in our ATG [notebook](https://github.com/ReactionMechanismGenerator/RMG-database/blob/main/scripts/BM%20tree%20fitting%20notebook.ipynb) as well as our ATG [script](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/main/scripts/generateTree.py#L70-L72) but I also appended my thermo libraries to the front which have very good calculations. I made a mistake the first time I pushed this branch in that I only used ` 'ENI_1dHR', 'primaryThermoLibrary'` the first time around.

**Review by amarkpayne — APPROVED** [review]
Thanks for the PR @kspieks ! I'll merge this in as soon as the tests pass

**Comment by xiaoruiDong** [comment]
Merged as both checks passed

**Pull request merged**
