### PR TITLE
Remove template that allows forbidden [2pi+2pi] thermal cycloaddition reaction for two C=C

### PR DESCRIPTION
**Pull request by hwpang**
As stated in issue [https://github.com/ReactionMechanismGenerator/RMG-Py/issues/1761](url) under RMG-Py, the current template allows forbidden [2pi+2pi] thermal cycloaddition reaction for two C=C.

I've removed the L2 template md_db in groups.py. I also removed the kinetics of C2H4 + C2H4 <=> C4H8 [1] in rules.py since this reaction is the total rate of two elementary reactions, i.e. two ethylene form a diradical via 1,4_Linear_birad_scission, and then become cyclobutane via diradical recombination.

[1] Quick, L. M., D. A. Knecht, and M. H. Back. "Kinetics of the Formation of Cyclobutane from Ethylene." International Journal of Chemical Kinetics 4.1 (1972): 61-68.

### CODE REVIEW

**Comment by mjohnson541** [comment]
Can you rebase?

**Comment by hwpang** [comment]
> Can you rebase?

Rebased! Thanks!

**Comment by mjohnson541** [comment]
Did you push the rebase to the remote?

**Comment by mjohnson541** [comment]
You don't have the merge from the peroxy_rates branch on this branch. You may need to pull changes from origin to your master before you rebase.

**Comment by hwpang** [comment]
> You don't have the merge from the peroxy_rates branch on this branch. You may need to pull changes from origin to your master before you rebase.

I rebased. Thanks.

**Pull request merged**
