### PR TITLE
Refit s2_5_6_triene_1_3_6 polycyclic group

### PR DESCRIPTION
**Pull request by hwpang**
Two polycyclic groups were refitted.

## For s2_5_6_triene_1_3_6 group

This species's thermo estimation was found to be 25 kcal/mol difference from cbs-qb3 calculation. 
image

The estimated thermo data from the original s2_5_6_triene_1_3_6 group was 
H298 = 24.852999999999994 kcal/mol
S298 = 79.5532 cal/mol*K

While the thermo data from my cbs-qb3 calculation with AECs & BACs is
H298 = 50.775479779618856 kcal/mol
S298 = 84.27639136762846 cal/mol*K

I think there are some typo from the original group entry, since I didn't get the same group entry by fitting from the species pdt32 from C10H11 library.

## For s3_5_5_ene_1 group

This species's thermo estimation was found to be 8 kcal/mol difference from cbs-qb3 calculation.
image

The estimated thermo from original s3_5_5_ene_1 group was
H298 = 52.19664435946462 kcal/mol
S298 = 101.37419694072656 cal/mol*K

While the thermo data from my cbs-qb3 calculation with AECs & BACs is
H298 = 43.32804088266143 kcal/mol
S298 = 101.35524677371652 cal/mol*K

The original data source "molecule s3_5_5_ene_1 from Bicyclics_QM_190_isomorphic library" was not found so I didn't do a comparison.

### CODE REVIEW

**Comment by xiaoruiDong** [comment]
@hwpang Thanks for the contribution

1. Regarding the first group, do you know which conformer did you calculate? Cis or trans (regarding carbon 5 and carbon 9)? By MMFF94S, a rough estimation of E(trans) - E(cis) = 200 - 132 = 16.25 kcal/mol.
2. Regarding the second group, there are also multiple conformers, benzene ring being cis or trans to the one-carbon-bridge. Maybe you want to check it as well?

Let me know your finding.

**Comment by hwpang** [comment]
> @hwpang Thanks for the contribution
> 
> 1. Regarding the first group, do you know which conformer did you calculate? Cis or trans (regarding carbon 5 and carbon 9)? By MMFF94S, a rough estimation of E(trans) - E(cis) = 200 - 132 = 16.25 kcal/mol.
> 2. Regarding the second group, there are also multiple conformers, benzene ring being cis or trans to the one-carbon-bridge. Maybe you want to check it as well?
> 
> Let me know your finding.

Thanks for the review & comment on the conformer forms!!

The conformer I calculated for the first group is the cis form (see figure). As you mentioned, a rough estimation from MMFF94s shows E(trans) - E(cis) = 200 - 132 = 16.25 kJ/mol (I think the unit should be kJ/mol). The cis form should be the lowest energy conformer for this species.

image

As for the second group, the conformer I calculated is trans to the one carbon bridge. A rough estimation from MMFF94s shows that E(trans) - E(cis) = 273 - 266 = 7 kJ/mol. Unfortunately, the ARC conformer search didn't find the lowest energy conformer for this species. I will remove the second commit.

**Comment by hwpang** [comment]
@xiaoruiDong Actually, I'll do a cbs-qb3 calculation for the cis form of the second conformer to compare. Please hold on merging this branch until the comparison is done. Thanks!!

**Comment by hwpang** [comment]
@xiaoruiDong The cbs-qb3 calculation shows that E(cis) - E(trans) < 0.001 hartree (I used the cis form that gives 266 kJ/mol from MMFF94s as initial xyz). I think this confirms that the trans form is the lower energy conformer. I added the second commit back.

**Comment by xiaoruiDong** [comment]
Thanks! @hwpang, can you also report the GA estimation on these two species with your new commits? The difference of S298 between your calculation and original GAV is not very big. But the updated S298 of `s2_5_6_triene_1_3_6` group is way larger than its original value. I know it is what fitting gives. I just want to make sure this new value leads to a good estimation. Thanks.

**Comment by hwpang** [comment]
> Thanks! @hwpang, can you also report the GA estimation on these two species with your new commits? The difference of S298 between your calculation and original GAV is not very big. But the updated S298 of `s2_5_6_triene_1_3_6` group is way larger than its original value. I know it is what fitting gives. I just want to make sure this new value leads to a good estimation. Thanks.

Thanks for the review @xiaoruiDong ! I think the GAV seems to be different because the new group is written in SI unit. For the first species, the difference in S298 from cbs-qb3 and the original GA estimation is 4.7231 cal/mol*K, and the difference in S298 from the new GAV and the old GAV is 4.7754 cal/mol*K. 

The GA estimation from the new group for the first species is 
H298 = 50.77548279158699 kcal/mol
S298 = 84.27640535372849 cal/mol*K

Comparison of cbs-qb3 calcs with the new GA estimated thermo
Difference in H298 = -3.0e-06 kcal/mol
Difference S298 = -1.3e-05 cal/mol*K

The GA estimation from the new group for the second species is 
H298 = 43.32804971319312 kcal/mol
S298 = 101.35531548757169 cal/mol*K

Comparison of cbs-qb3 calcs with the new GA estimated thermo
Difference in H298 = -8.8e-06 kcal/mol
Difference S298 = -6.8e-05 cal/mol*K

**Review by xiaoruiDong — APPROVED** [review]
Thanks!

**Pull request merged**
