### PR TITLE
Generate Intra_R_Add_Endocyclic/Exocyclic from the ring opening direction

### PR DESCRIPTION
**Pull request by hwpang**
See https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2306 for details.

### CODE REVIEW

**Comment by kspieks** [comment]
Thanks @hwpang for this PR! I looked over everything and it looks great. As a note to future reviewers, ATG rewrites the root node in a different order so it appears that it was changed but it still defines the same group. We had a very productive RMG hackathon :)

**Comment by kspieks** [comment]
Note that the build and test failed but this is error is fixed in RMG-Py [PR #2306](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2306/commits/6a943b65f41858ecc17641ba20f677942a8bd7ae)

**Comment by hwpang** [comment]
New push merges the changes from https://github.com/ReactionMechanismGenerator/RMG-database/pull/580 to make sure this PR actually resolves the error in RMG-tests.

**Comment by hwpang** [comment]
New push rewords the commits to be more informative.

**Comment by hwpang** [comment]
RMG-tests failed at the benchmark branch (the current main) due to the error that should be resolved once https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2306 and this PR are merged.

**Comment by kspieks** [comment]
I agree with @hwpang. The test fails due to the following [error](https://github.com/ReactionMechanismGenerator/RMG-tests/runs/6375575951?check_suite_focus=true#step:6:150):
```
    raise UndeterminableKineticsError(reaction, message=msg)
rmgpy.exceptions.UndeterminableKineticsError: (TemplateReaction(reactants=[Molecule(smiles="C1=C[CH]C=CC=1")], products=[Molecule(smiles="[CH]1C2=CC=CC12")], pairs=[[Molecule(smiles="C1=C[CH]C=CC=1"), Molecule(smiles="[CH]1C2=CC=CC12")]], family='Intra_R_Add_Exocyclic'), 'Kinetics could not be determined. Unable to find matching template for reaction <Molecule "C1=C[CH]C=CC=1"> <=> <Molecule "[CH]1C2=CC=CC12"> in reaction family <KineticsGroups "Intra_R_Add_Exocyclic/groups">.Trying to match [<Entry index=0 label="Root">] but matched []')
```

However, if I checkout this branch and the corresponding `fix_intra_r_add_endocyclic` from https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2306, there are no issues with this reaction as shown in the notebook below. Thus, I will merge this PR
[20220510_test_exocyclic.ipynb.zip](https://github.com/ReactionMechanismGenerator/RMG-database/files/8665759/20220510_test_exocyclic.ipynb.zip)

**Pull request merged**
