### PR TITLE
added solvent SMILES representation

### PR DESCRIPTION
**Pull request by yunsiechung**
I added SMILES for all the solvents. This will allow RMG liquid phase reactions to recognize the solvent by its molecular structure.

In order for this commit to pass all the tests, the RMG-Py must be updated with my new code in my latest RMG-Py pull request.

Could someone check my RMG-Py pull request first? If that can be merged, could someone check and merge this? 

Thank you!

### CODE REVIEW

**Comment by bslakman** [comment]
Do we have to do something special to reinitiate the travis tests now that the RMG-Py has been updated?

**Comment by connie** [comment]
You can go into travis and hit the restart build button on the right hand side.  
Alternatively just rebase and force push and the travis will restart.

**Comment by connie** [comment]
What is this mention-bot?

**Comment by rwest** [comment]
I set it up. Mentioned it in some pull request comment. It wasn't working at the time but seems it is fixed now. If it becomes annoying we can disable in the organization settings web hooks. 

It suggests code reviewers by looking at who last edited the same or nearby code.

**Comment by rwest** [comment]
Restarting doesn't work - it needs a rebase (the .travis.yml was fixed recently on master)

**Pull request merged**
