### PR TITLE
Halogens transport

### PR DESCRIPTION
**Pull request by davidfarinajr**
Added NIST transport library for fluorines and added new halogen transport groups

### CODE REVIEW

**Comment by davidfarinajr** [comment]
This PR goes with RMGPy PR https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2098

**Review by ChrisBNEU — APPROVED** [review]
These look fine. I spot checked a few against the source (Devotta et al and Joback).

**Review by rwest — CHANGES_REQUESTED** [review]
I just asked for some more metadata. Otherwise looks good (I'm trusting you and Chris's review). I rebased to trigger the tests, but the "RMG-tests" ones will probably fail because there's a hyphen in your branch name.

**Comment by davidfarinajr** [comment]
Ok, I added metadata for the NIST Fluorine transport library, I think this PR is ready

**Review by rwest — APPROVED** [review]

**Pull request merged**
