### PR TITLE
Automatic Tree generation for R_Recombination

### PR DESCRIPTION
**Pull request by mjohnson541**

### CODE REVIEW

**Comment by mliu49** [comment]
Are the changes to the training folder simply because it was machine written?

I think if you were to remove those changes for now, we can merge this. There are some unicode issues with the training reactions files which I don't particularly want to deal with right now.

**Comment by mjohnson541** [comment]
Yes, there were no changes in the substance of the training depository.

**Comment by mjohnson541** [comment]
I've removed the training depository changes.

**Comment by mliu49** [comment]
Thanks!

**Pull request merged**
