### PR TITLE
Fix Intra_R_Add_Endocyclic/Exocyclic by enumerating backbones

### PR DESCRIPTION
**Pull request by hwpang**
@kspieks and I's previous attempt (https://github.com/ReactionMechanismGenerator/RMG-database/pull/579) to solve this issue (https://github.com/ReactionMechanismGenerator/RMG-database/issues/577) address that issue specifically, but it instead causes the following error due to the ambiguity of the root node of Intra_R_Add_Endocyclic without specifying backbones.

```
rmgpy.exceptions.UndeterminableKineticsError: (TemplateReaction(reactants=[Molecule(smiles="[O]S1OO1")], products=[Molecule(smiles="[O]OS=O")], pairs=[[Molecule(smiles="[O]S1OO1"), Molecule(smiles="[O]OS=O")]], family='Intra_R_Add_Endocyclic'), 'Kinetics could not be determined. Unable to find matching template for reaction <Molecule "[O]S1OO1"> <=> <Molecule "[O]OS=O"> in reaction family <KineticsGroups "Intra_R_Add_Endocyclic/groups">.Trying to match [<Entry index=0 label="Root">] but matched []')
```

Per Bill's suggestion, here I break up that both families into a lot of subfamilies by counting the atoms between the interacting functional groups. I used a custom script to run ATG such that it can automatically generate these subfamilies and place them under a logic node. I attempted both ring opening and ring closing direction, and found no obvious differences. I chose the ring closing direction to maintain the nice feature of having all the families in the exothermic direction. The script is attached below for reviewer's convenience.

```
import sys
sys.path.insert(0,"/home/gridsan/hwpang/Software/RMG-Py/")

from rmgpy.rmg.main import RMGDatabase
from rmgpy import settings
from rmgpy.molecule.molecule import Molecule
from rmgpy.data.base import Entry, LogicOr
from rmgpy.molecule.atomtype import ATOMTYPES
from rmgpy.molecule.group import Group, GroupBond, GroupAtom

import time
from collections import OrderedDict
from copy import deepcopy

database = RMGDatabase()
database.load(
    path=settings["database.directory"],
    thermo_libraries=['Spiekermann_refining_elementary_reactions', 'Klippenstein_Glarborg2016', 'BurkeH2O2', 'thermo_DFT_CCSDTF12_BAC', 'DFT_QCI_thermo',
                     'primaryThermoLibrary', 'primaryNS', 'NitrogenCurran', 'NOx2018', 'FFCM1(-)',
                     'SulfurLibrary', 'SulfurGlarborgH2S', 'SABIC_aromatics'],
    transport_libraries=[],
    reaction_libraries=[],
    seed_mechanisms=[],
    kinetics_families="default",
    kinetics_depositories=['training'],
    # frequenciesLibraries = self.statmechLibraries,
    depository=False,  # Don't bother loading the depository information, as we don't use it
)

# make group for the ring opening direction
def make_group_exo(backbone):
    assert backbone != 0
    group_atoms = {}
    group_atoms["*1"] = GroupAtom(atomtype=[ATOMTYPES["R!H"]],
                                     radical_electrons=[0],
                                     label='*1')
    group_atoms["*2"] = GroupAtom(atomtype=[ATOMTYPES["R!H"]],
                                     radical_electrons=[0],
                                     label='*2')
    group_atoms["*3"] = GroupAtom(atomtype=[ATOMTYPES["R!H"]],
                                     radical_electrons=[1],
                                     label='*3')
    for bb in range(1,backbone+1):
        group_atoms[f"*{bb+3}"] = GroupAtom(atomtype=[ATOMTYPES["R!H"]],
                                            radical_electrons=[0],
                                           )
        
    keys = sorted(list(group_atoms.keys()))
    group = Group(atoms=[group_atoms[key] for key in keys])
    group.add_bond(GroupBond(group_atoms["*2"],group_atoms["*3"],order=[1.0,1.5,2.0]))
    group.add_bond(GroupBond(group_atoms["*1"],group_atoms["*2"],order=[1.0,1.5]))
    
    if backbone != -1:
        
        for bb in range(1,backbone+1):
            if bb == 1:
                group.add_bond(GroupBond(group_atoms["*1"],group_atoms["*4"],order=[1.0,1.5,2.0,3.0]))
            else:
                group.add_bond(GroupBond(group_atoms[f"*{(bb-1)+3}"],group_atoms[f"*{bb+3}"],order=[1.0,1.5,2.0,3.0]))

        group.add_bond(GroupBond(group_atoms[f"*{backbone+3}"],group_atoms[f"*2"],order=[1.0,1.5,2.0,3.0]))
    group.update()
    return group
make_group_exo(1)

# make group for ring closing direction
def make_group(backbone):
    group_atoms = {}
    group_atoms["*1"] = GroupAtom(atomtype=[ATOMTYPES["R!H"]],
                                     radical_electrons=[1],
                                     label='*1')
    group_atoms["*2"] = GroupAtom(atomtype=[ATOMTYPES["R!H"]],
                                     radical_electrons=[0],
                                     label='*2')
    group_atoms["*3"] = GroupAtom(atomtype=[ATOMTYPES["R!H"]],
                                     radical_electrons=[0],
                                     label='*3')
    for bb in range(1,backbone+1):
        group_atoms[f"*{bb+3}"] = GroupAtom(atomtype=[ATOMTYPES["R!H"]],
                                            radical_electrons=[0],
                                           )
        
    keys = sorted(list(group_atoms.keys()))
    group = Group(atoms=[group_atoms[key] for key in keys])
    group.add_bond(GroupBond(group_atoms["*2"],group_atoms["*3"],order=[1.5,2.0,3.0]))
    
    if backbone != -1:
        
        for bb in range(1,backbone+1):
            if bb == 1:
                group.add_bond(GroupBond(group_atoms["*1"],group_atoms["*4"],order=[1.0,1.5,2.0,3.0]))
            else:
                group.add_bond(GroupBond(group_atoms[f"*{(bb-1)+3}"],group_atoms[f"*{bb+3}"],order=[1.0,1.5,2.0,3.0]))
        if backbone != 0:
            group.add_bond(GroupBond(group_atoms[f"*2"],group_atoms[f"*{backbone+3}"],order=[1.0,1.5,2.0,3.0]))
        else:
            group.add_bond(GroupBond(group_atoms[f"*2"],group_atoms[f"*1"],order=[1.0,1.5,2.0,3.0]))
    group.update()
    return group
display(make_group(-1))
display(make_group(0))
display(make_group(1))

max_backbone = 10

family_name = "Intra_R_Add_Exocyclic"

if family_name == "Intra_R_Add_Exocyclic":
    backbone_range = range(1,max_backbone+1)
elif family_name == "Intra_R_Add_Endocyclic":
    backbone_range = range(max_backbone+1)

family = database.kinetics.families[family_name]

family.clean_tree_rules()
family.groups.entries = {entry.label: entry for entry in family.groups.entries.values() if entry.index == -1}

family.groups.entries["Root"] = Entry(
    index=1,
    label="Root",
    item=make_group(-1),
)

family.groups.top = [family.groups.entries["Root"]]
family.forward_template.reactants = [family.groups.entries['Root']]

for backbone in backbone_range:
    label = f"Backbone{backbone}"
    family.groups.entries[label] = Entry(
        index=backbone+1,
        label=label,
        item=make_group(backbone),
        parent=family.groups.entries["Root"],
    )
    family.groups.entries["Root"].children.append(family.groups.entries[label])

start = time.time()
templateRxnMap = family.get_reaction_matches(thermo_database=database.thermo, 
                                             remove_degeneracy=True,
                                             fix_labels=True, 
                                             exact_matches_only=True, 
                                             get_reverse=True)
end = time.time()

assert templateRxnMap["Root"]==[]

start = time.time()
family.generate_tree(thermo_database=database.thermo,
                     nprocs=1,
                     new_fraction_threshold_to_reopt_node=0.25,
                     max_batch_size=800,
                     extension_iter_max=2,
                     extension_iter_item_cap=100)

end = time.time()
print(end-start)

start = time.time()
family.check_tree()
end = time.time()
print(end-start)

start = time.time()
family.regularize(thermo_database=database.thermo)
end = time.time()
print(end-start)

start = time.time()
templateRxnMap = family.get_reaction_matches(thermo_database=database.thermo,remove_degeneracy=True,
                                             get_reverse=True,exact_matches_only=False,fix_labels=True)
end = time.time()
print(end-start)

start = time.time()
family.make_bm_rules_from_template_rxn_map(templateRxnMap,nprocs=8)
end = time.time()
print(end-start)

start = time.time()
family.check_tree()
end = time.time()
print(end-start)

start = time.time()
errors,uncertainties = family.cross_validate(iters=0,random_state=5,folds=0,ascend=False)
end = time.time()
print(end-start)

import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('TkAgg')
%matplotlib inline
import numpy as np

plt.figure(figsize=(10,8))
plt.hist(np.abs(list(errors.values())),bins=30, density=True)
plt.title('Decision Tree Estimator',fontsize=18)
#plt.ylim(0,.4)
plt.xlim(0,15)
plt.ylabel('Probability density',fontsize=18)
plt.xlabel(r'$|Ln(k_{est}/k_{rxn})|$',fontsize=18)


family.groups.entries["Root"].item=LogicOr([f"Backbone{backbone}" for backbone in backbone_range], invert=False)

for backbone in backbone_range:
    label = f"Backbone{backbone}"
    if label in family.groups.entries:
        family.groups.entries[label].item=make_group(backbone)
    else:
        family.groups.entries[label] = Entry(
                index=len(family.groups.entries)+1,
                label=label,
                item=make_group(backbone),
                parent=family.groups.entries["Root"],
            )
        family.groups.entries["Root"].children.append(family.groups.entries[label])
    if not family.rules.entries.get(label,[]): 
        family.rules.entries[label] = deepcopy(family.rules.entries["Root"])
        family.rules.entries[label][0].index = len(family.rules.entries)+1
        family.rules.entries[label][0].label = label

k=0
for entry in family.groups.entries.values():
    if entry.index != -1:
        entry.index = k
        k+=1
    
k=0
for entry_list in family.rules.entries.values():
    if entry_list:
        entry = entry_list[0]
        if entry.index != -1:
            entry.index = k
            k+=1

import os
save_path = os.path.join(settings['database.directory'], 'kinetics', 'families', family.name)
print(save_path)

family.save(save_path)

# reload the database for testing
database = RMGDatabase()
database.load(
    path=settings["database.directory"],
    thermo_libraries=['Spiekermann_refining_elementary_reactions', 'Klippenstein_Glarborg2016', 'BurkeH2O2', 'thermo_DFT_CCSDTF12_BAC', 'DFT_QCI_thermo',
                     'primaryThermoLibrary', 'primaryNS', 'NitrogenCurran', 'NOx2018', 'FFCM1(-)',
                     'SulfurLibrary', 'SulfurGlarborgH2S', 'SABIC_aromatics'],
    transport_libraries=[],
    reaction_libraries=[],
    seed_mechanisms=[],
    kinetics_families="default",
    kinetics_depositories=['training'],
    # frequenciesLibraries = self.statmechLibraries,
    depository=False,  # Don't bother loading the depository information, as we don't use it
)
family = database.kinetics.families[family_name]


# some of these reactions failed both before and after this PR: https://github.com/ReactionMechanismGenerator/RMG-database/pull/579
# none of them failed with this change
print(family.generate_reactions(
    reactants=[Molecule().from_smiles("C=CC[CH2]")],
    products=[Molecule().from_smiles("C1C[CH]C1")],
))
print(family.generate_reactions(
    reactants=[Molecule().from_smiles("C1C[CH]C1")],
    products=[Molecule().from_smiles("C=CC[CH2]")],
))
print(family.generate_reactions(
    reactants=[Molecule().from_smiles("C=CC[CH2]")],
    products=[Molecule().from_smiles("C1CC1[CH2]")],
))
print(family.generate_reactions(
    reactants=[Molecule().from_smiles("C1CC1[CH2]")],
    products=[Molecule().from_smiles("C=CC[CH2]")],
))

print(family.generate_reactions(
    reactants=[Molecule().from_smiles("[O]S1OO1")],
    products=[Molecule().from_smiles("[O]OS=O")],
))

print(family.generate_reactions(
    reactants=[Molecule().from_smiles("[O]OS=O")],
    products=[Molecule().from_smiles("[O]S1OO1")],
))

print(family.generate_reactions(reactants=[Molecule().from_smiles('C1=C[CH]C=CC=1')],
                                products=[Molecule().from_smiles('[CH]1C2=CC=CC12')],
))

print(family.generate_reactions(reactants=[Molecule().from_smiles('[CH]1C2=CC=CC12')],
                                products=[Molecule().from_smiles('C1=C[CH]C=CC=1')],
))



import logging
# List of the each top node's descendants (including the top node)
top_descendants = []
for topNode in family.get_root_template():
    nodes = [topNode]
    nodes.extend(family.groups.descendants(topNode))
    top_descendants.append(nodes)

top_group_order = ';'.join(topNode.label for topNode in family.get_root_template())
tst1 = []
tst2 = []
for label, entries in family.rules.entries.items():
    for entry in entries:
        nodes = label.split(';')
        for i, node in enumerate(nodes):
            tst1.append((node in family.groups.entries,
                         "In {family} family, no group definition found for label {label} in rule "
                         "{entry}".format(family=family_name, label=node, entry=entry)))
            tst2.append((family.groups.entries[node] in top_descendants[i],
                         "In {family} family, rule {entry} was found with groups out of order. "
                         "The correct order for a rule should be subgroups of {top}.".format(
                             family=family_name, entry=entry, top=top_group_order)))
boo = False
for i in range(len(tst1)):
    if not tst1[i][0]:
        logging.error(tst1[i][1])
        boo = True
    if not tst2[i][0]:
        logging.error(tst2[i][1])
        boo = True

if boo:
    raise ValueError("Error occured in databaseTest. Please check log warnings for all error messages.")



tst = []
tst1 = []
tst2 = []
tst3 = []
for nodeName, nodeGroup in family.groups.entries.items():
    tst.append(('[' in nodeName or ']' in nodeName,
                "Group {group} in {family} family contains square brackets [ ] in the label, which are "
                "not allowed.".format(group=nodeName, family=family_name)))
    ascend_parent = nodeGroup

    # Check whether the node has proper parents unless it is the top reactant or product node
    while ascend_parent not in family.groups.top and ascend_parent not in family.forward_template.products:
        child = ascend_parent
        ascend_parent = ascend_parent.parent
        tst1.append((ascend_parent is not None,
                     "Group {group} in {family} family was found in the tree without a proper parent.".format(
                         group=child, family=family_name)))
        tst2.append((child in ascend_parent.children,
                     "Group {group} in {family} family was found in the tree without a proper parent.".format(
                         group=nodeName, family=family_name)))
        tst3.append((child is ascend_parent,
                     "Group {group} in {family} family is a parent to itself".format(
                         group=nodeName, family=family_name)))

boo = False
for i in range(len(tst)):
    if tst[i][0]:
        logging.error(tst[i][1])
        boo = True
for i in range(len(tst1)):
    if not tst1[i][0]:
        logging.error(tst1[i][1])
        boo = True
    if not tst2[i][0]:
        logging.error(tst2[i][1])
        boo = True
    if tst3[i][0]:
        logging.error(tst3[i][1])
        boo = True

if boo:
    raise ValueError("Error occured in databaseTest. Please check log warnings for all error messages.")

```

### CODE REVIEW

**Comment by hwpang** [comment]
Fixed a minor error where the previous script forgot to append eliminated backbone nodes as the root's children, which caused the generated tree to fail the database test. The new push should fix this. The script is updated as well.

**Review by kspieks — CHANGES_REQUESTED** [review]
@hwpang Thanks for this PR that changes the root node back to the previous template and adds backbones. I ran your code locally and everything worked fine so this PR should be close. However, the tests just failed due to
```
 rmgpy.exceptions.UndeterminableKineticsError: (TemplateReaction(reactants=[Molecule(smiles="[O]S1OO1")], products=[Molecule(smiles="[O]OS=O")], pairs=[[Molecule(smiles="[O]S1OO1"), Molecule(smiles="[O]OS=O")]], family='Intra_R_Add_Endocyclic'), 'Kinetics could not be determined. Unable to find matching template for reaction <Molecule "[O]S1OO1"> <=> <Molecule "[O]OS=O"> in reaction family <KineticsGroups "Intra_R_Add_Endocyclic/groups">.Trying to match [<Entry index=0 label="Root">] but matched []')
```

I think this reaction should only match exocyclic? Is this an issue with the backbones for endocyclic allowing this reaction?

As a minor point, I was seeing some lines like `*2 R!H u0 {1,[S,B,D,T,Q]} {3,[B,D,T,Q]}`  or even `R!H ux {2,[S,D,T,B,Q]} {5,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}`. I'm not sure how an atom could have quadruple bonds to 3 different atoms. Is it worth removing `4.0` from the list of bond orders? 


As a minor point, can you re-run your code to include my thermo library? i.e.
```
thermo_libraries=['Spiekermann_refining_elementary_reactions', 'Klippenstein_Glarborg2016', 'BurkeH2O2', 'thermo_DFT_CCSDTF12_BAC', 'DFT_QCI_thermo',
                     'primaryThermoLibrary', 'primaryNS', 'NitrogenCurran', 'NOx2018', 'FFCM1(-)',
                     'SulfurLibrary', 'SulfurGlarborgH2S', 'SABIC_aromatics'],
```
Doing so will barely change the rate rules since it should only impact one reaction, but technically I did add one reaction to each of the endo and exo training reactions and their corresponding thermo is in my thermo library, which the tree should use when calculating the reverse rate.

**Comment by hwpang** [comment]
@kspieks Thanks for the review! The test failed on the current main branch. The error occurred when RMG-tests is running the benchmark job, which is using the main branch RMG-database, which has our previous fix (https://github.com/ReactionMechanismGenerator/RMG-database/pull/579) that introduces this error in the first place, which is the error this PR trying to fix. This error can be found in other recent PRs (e.g. https://github.com/ReactionMechanismGenerator/RMG-tests/runs/6394170989?check_suite_focus=true).

As for the Q bond, I was trying to make the backbone head node as general as possible. The later Q bonds are introduced by the ATG but not by my code. I can remove the Q bond from the backbone head nodes.

I will include your library and generate the trees again! Thanks!

**Comment by hwpang** [comment]
@kspieks The new push should address all the comments!

**Comment by kspieks** [comment]
Thanks again for this PR! I'll merge now.

Just to respond to the other comments, thanks I'd forgotten that RMG-tests pulls from main. Thanks I must've misunderstood. I thought removing `4.0` from the list of bond orders removed Q when I tested locally. Yea ATG has introduced Q bonds for other families (like my previous PRs). I was meaning to look into it in the future since I don't remember if bond orders were as easily accessible in the ATG notebook as they are in your script.

**Pull request merged**
