### PR TITLE
Halogens thermo

### PR DESCRIPTION
**Pull request by davidfarinajr**
this PR replaces https://github.com/ReactionMechanismGenerator/RMG-database/pull/465 which supersedes https://github.com/ReactionMechanismGenerator/RMG-database/pull/434

This PR adds new thermo libraries and improves RMG's ability to estimate thermochemistry using group additivity for CHON and CHO-(F,Cl,Br) species. The new thermo groups were primarily derived from the new G4 thermo libraries added in this PR.

What has been added:

### New thermo libraries:
CHOF_G4
CHOCl_G4
CHOBr_G4
CHOFCl_G4
CHOClBr_G4
CHOFBr_G4
CHOFClBr_G4
Chlorination
halogens
2-BTP
2-BTP_G4
### New thermo groups:
group.py
radical.py
longDistanceInteraction_noncyclic.py

### Reviewing the commit history
- the first batch of commits starting with `added` simply adds new thermo libraries
- For the thermo groups, the commits were arranged as follows to try to ease the reviewing process and tidy-up the git history
i) machine write the thermo groups file (group, radical, longDistanceInteraction_noncylic) by loading it into memory and then saving (without any alterations)
ii) the `derived ...` commits add the new groups and attempt to preserve the order of the existing groups (so the entire file is not re-written in git commit)
iii) machine write the new groups without any alterations

### SIMULTANEOUS PR
with ReactionMechanismGenerator/RMG-Py#2120

### CODE REVIEW

**Comment by davidfarinajr** [comment]
Oops, the missing GAV group test failed. Need to open RMGpy PR to change that one.

**Comment by davidfarinajr** [comment]
regression test data
[rmg_thermo_libraries_gav_estimates.csv](https://github.com/ReactionMechanismGenerator/RMG-database/files/6408740/rmg_thermo_libraries_gav_estimates.csv)
and results
[RMG_libraries_gav_pr_master.pdf](https://github.com/ReactionMechanismGenerator/RMG-database/files/6408739/RMG_libraries_gav_pr_master.pdf)

PR groups slightly improve CHO and more significantly improve N-containing and Hal-containing molecules

**Comment by davidfarinajr** [comment]
> Oops, the missing GAV group test failed. Need to open RMGpy PR to change that one.

This PR https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2120, changes the molecule for the missing thermo group test so that it passes

**Comment by davidfarinajr** [comment]
> In the thermo libraries (eg. 2-BTP_G4) I notice the labels are like smiles strings but with double bonds changed from `=` to `D`. Is this to get around a limitation in RMG, or some other part of your toolchain?

Yes, that's right, the labels are `smiles.replace('=','D')`.  This is true for all the `X_G4` thermo libraries that I added.  I believe I did this because we use `reactants = products` and use `=` to split a reaction string into reactants and products.

**Comment by rwest** [comment]
These diffs are so large it was easiest to review by doing an interactive rebase and inspecting the changes and files at each commit. While doing so I made a few changes to comments and commit messages. Our importer script tries to save comments from the chemkin file and add them to the `longDesc` field of the entries it creates, but some "comments" are in fact just stuff the model authors should have deleted, and so I deleted them.
Otherwise, this all looks good to me. 
Thanks for doing the regression tests (posted a few comments above). Nice that the halogenated enthalpies have gone from a mean absolute error of 67 kcal/mol down to 2.7 kcal/mol 😀 

Will just wait for the tests to run again after my rebase.

**Review by rwest — APPROVED** [review]

**Comment by rwest** [comment]
David, please take a quick look through the log files from the rmg-tests run, eg. [here](https://travis-ci.org/github/ReactionMechanismGenerator/RMG-tests/builds/769965924).

There are some significant changes, eg.
```
2917 Non-identical thermo!
2918 original:	[O]C=N
2919 tested:	[O]C=N
2920 Hf(300K)  |S(300K)   |Cp(300K)  |Cp(400K)  |Cp(500K)  |Cp(600K)  |Cp(800K)  |Cp(1000K) |Cp(1500K) 
2921       1.87|     59.42|     11.57|     13.74|     15.85|     17.75|     20.56|     22.12|     24.34
2922     -48.13|     58.72|     10.65|     13.50|     16.28|     18.63|     21.45|     22.40|     24.31
2923 thermo: Thermo library: thermo_DFT_CCSDTF12_BAC + radical(RC=COJ)
2924 thermo: Thermo library: thermo_DFT_CCSDTF12_BAC + radical(N=COJ)
```

Now the whole point of this PR is to introduce significant changes (significant improvements are significant changes) but we should just do one last check that these are indeed improvements.  Anyway, these logs are a good way to see what impact the PR has.

**Comment by davidfarinajr** [comment]
Lets merge this one first https://github.com/ReactionMechanismGenerator/RMG-database/pull/478.  Its important to add `NO` to primaryThermoLibrary because if GAV estimate is poor, it can mess with the Birad_R_recombination rates.  Because of cancel of errors with master thermo groups, the GAV free energy is not too bad (https://rmg.mit.edu/database/thermo/molecule/multiplicity%202%0A1%20N%20u1%20p1%20c0%20%7B2,D%7D%0A2%20O%20u0%20p2%20c0%20%7B1,D%7D%0A), but its worse with these groups

**Comment by davidfarinajr** [comment]
I also need to figure out what's going on with `radical(N=COJ)` group.  Its seems a bit low

**Comment by davidfarinajr** [comment]
Screen Shot 2021-05-07 at 8 15 51 PM

for N-containing species in qm9 g4mp2 test set.  MAE drops from ~20 kcal/mol to ~4 with new groups

**Comment by davidfarinajr** [comment]
> So #478 is merged (adding stuff to primaryThermoLibrary), this has been rebased, and the tests have been re-run [here](https://travis-ci.org/github/ReactionMechanismGenerator/RMG-tests/builds/770509524). Any unexpected changes?

Checking that now

**Comment by davidfarinajr** [comment]
```
Non-identical thermo!
3411original:	[O-]O[SH2+]
3412tested:	[O-]O[SH2+]
3413Hf(300K)  |S(300K)   |Cp(300K)  |Cp(400K)  |Cp(500K)  |Cp(600K)  |Cp(800K)  |Cp(1000K) |Cp(1500K) 
3414    156.85|     39.31|     11.87|     12.00|     12.04|     12.22|     13.19|     14.22|     14.52
3415    180.41|     30.06|      8.44|      8.59|      8.76|      8.95|      9.31|      9.60|      9.82
3416thermo: Thermo group additivity estimation: group(Sc) + group(O2s-(Cds-Cd)(Cds-Cd)) + group(O2s-CsCs)
3417thermo: Thermo group additivity estimation: group(Sc) + group(O2s-(Cds-Cd)(Cds-Cd)) + missing(O0sc-O2s)
3418
3419Non-identical thermo!
3420original:	[O-]O[SH+]O[O]
3421tested:	[O-]O[SH+]O[O]
3422Hf(300K)  |S(300K)   |Cp(300K)  |Cp(400K)  |Cp(500K)  |Cp(600K)  |Cp(800K)  |Cp(1000K) |Cp(1500K) 
3423    176.90|     77.23|     18.70|     19.28|     19.43|     19.67|     21.25|     23.04|     23.22
3424    200.46|     67.98|     15.30|     15.86|     16.10|     16.35|     17.40|     18.46|     18.47
3425thermo: Thermo group additivity estimation: group(Sc) + group(O2s-SsOs) + group(O2s-(Cds-Cd)(Cds-Cd)) + group(O2s-OsH) + group(O2s-CsCs) + radical(SOOJ)
3426thermo: Thermo group additivity estimation: group(Sc) + group(O2s-SsOs) + group(O2s-(Cds-Cd)(Cds-Cd)) + group(O2s-OsH) + missing(O0sc-O2s) + radical(SOOJ)
3427
3428Non-identical thermo!
3429original:	[O-]O[S+]=O
3430tested:	[O-]O[S+]=O
3431Hf(300K)  |S(300K)   |Cp(300K)  |Cp(400K)  |Cp(500K)  |Cp(600K)  |Cp(800K)  |Cp(1000K) |Cp(1500K) 
3432    156.85|     39.31|     11.87|     12.00|     12.04|     12.22|     13.18|     14.22|     14.52
3433    180.41|     30.06|      8.44|      8.59|      8.76|      8.95|      9.31|      9.60|      9.82
3434thermo: Thermo group additivity estimation: group(Sc) + group(O2s-(Cds-Cd)(Cds-Cd)) + group(O2s-CsCs) + missing(O2d-S4dc)
3435thermo: Thermo group additivity estimation: group(Sc) + group(O2s-(Cds-Cd)(Cds-Cd)) + missing(O0sc-O2s) + missing(O2d-S4dc)
3436The original model has 1 reactions that the tested model does not have.
3437rxn: O(4) + SO2(15) (+N2) <=> SO3(16) (+N2)		origin: primarySulfurLibrary
3438The tested model has 1 reactions that the original model does not have.
3439rxn: O(4) + SO2(15) (+N2) <=> SO3(16) (+N2)		origin: primarySulfurLibrary
```
🤔 changing the sulfur thermo was unintended.  This is because I changed the way we estimate thermo with `O0sc` atomtype so we use the neighboring atom instead
```
entry(
    index = 2269,
    label = "O0sc",
    group = 
"""
1 * O0sc u0
""",
    thermo = ThermoData(
        Tdata = ([300,400,500,600,800,1000,1500],'K'),
        Cpdata = ([0,0,0,0,0,0,0],'cal/(mol*K)'),
        H298 = (0,'kcal/mol'),
        S298 = (0,'cal/(mol*K)'),
    ),
    shortDesc = """""",
    longDesc = 
"""
This should be 0 since we account for this atom with
neighbor at the center
""",
)
```
but I do not have a group for `[S+]-O-[O-]`.  I could point to the `O2s-CsCs` which the master database uses

**Comment by davidfarinajr** [comment]
Do we have any sulfur reference data I could use as a benchmark?

**Comment by davidfarinajr** [comment]
For the Oxidation Comparison, the biggest thermo diffs are
```
Non-identical thermo!
2944original:	[O]C(=O)OO
2945tested:	[O]C(=O)OO
2946Hf(300K)  |S(300K)   |Cp(300K)  |Cp(400K)  |Cp(500K)  |Cp(600K)  |Cp(800K)  |Cp(1000K) |Cp(1500K) 
2947    -88.17|     72.48|     17.58|     21.37|     24.48|     26.77|     28.99|     29.44|     30.85
2948    -68.87|     72.50|     19.76|     22.30|     23.94|     24.92|     25.73|     26.18|     27.66
2949thermo: Thermo group additivity estimation: group(O2s-O2s(Cds-O2d)) + group(O2s-(Cds-O2d)H) + group(O2s-OsH) + group(Cds-OdOsOs) + radical(OC=OOJ)
2950thermo: Thermo group additivity estimation: group(O2s-O2s(Cds-O2d)) + group(O2s-(Cds-O2d)H) + group(O2s-(Os-CdOd)H) + group(Cds-OdOsOs) + radical(OC=OOJ)
2951
2952

Non-identical thermo!
3089original:	CC(=O)OO
3090tested:	CC(=O)OO
3091Hf(300K)  |S(300K)   |Cp(300K)  |Cp(400K)  |Cp(500K)  |Cp(600K)  |Cp(800K)  |Cp(1000K) |Cp(1500K) 
3092   -102.79|     75.67|     19.79|     24.83|     29.27|     32.94|     37.77|     40.28|     44.86
3093    -83.49|     75.69|     21.97|     25.75|     28.73|     31.09|     34.52|     37.01|     41.68
3094thermo: Thermo group additivity estimation: group(O2s-O2s(Cds-O2d)) + group(O2s-OsH) + group(Cs-(Cds-O2d)HHH) + group(Cds-OdCsOs)
3095thermo: Thermo group additivity estimation: group(O2s-O2s(Cds-O2d)) + group(O2s-(Os-CdOd)H) + group(Cs-(Cds-O2d)HHH) + group(Cds-OdCsOs)
```
Unfortunately I can't find ref for `[O]C(=O)OO` but `CC(=O)OO` is in a couple of RMG libraries here https://rmg.mit.edu/database/thermo/molecule/1%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B6,S%7D%20%7B7,S%7D%20%7B8,S%7D%0A2%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B3,D%7D%20%7B4,S%7D%0A3%20O%20u0%20p2%20c0%20%7B2,D%7D%0A4%20O%20u0%20p2%20c0%20%7B2,S%7D%20%7B5,S%7D%0A5%20O%20u0%20p2%20c0%20%7B4,S%7D%20%7B9,S%7D%0A6%20H%20u0%20p0%20c0%20%7B1,S%7D%0A7%20H%20u0%20p0%20c0%20%7B1,S%7D%0A8%20H%20u0%20p0%20c0%20%7B1,S%7D%0A9%20H%20u0%20p0%20c0%20%7B5,S%7D%0A.  The PR thermo groups get closer to library H298 by fixing this issue https://github.com/ReactionMechanismGenerator/RMG-database/issues/460

**Comment by davidfarinajr** [comment]
just did G4 calc for `[O]C(=O)OO`:
```
#   Enthalpy of formation (298 K)   =   -61.935 kcal/mol
#   Entropy of formation (298 K)    =    74.503 cal/(mol*K)
```
So new PR groups get H298 closer here (-68.87 vs -88.17)

**Comment by davidfarinajr** [comment]
G4 H298 for `[O-]O[SH2+]` is 44.3 kcal/mol.  So we did make it worse (156.85 -> 180.41 kcal/mol) but it was already not very good to start with

**Comment by davidfarinajr** [comment]
```entry(
    index = 2366,
    label = "Sc",
    group = 
"""
1 * S ux c+1
""",
    thermo = ThermoData(
        Tdata = ([300,400,500,600,800,1000,1500],'K'),
        Cpdata = ([5,5,5,5,5,5,5],'cal/(mol*K)','+|-',[1,1,1,1,1,1,1]),
        H298 = (200,'kcal/mol','+|-',1),
        S298 = (20,'cal/(mol*K)','+|-',1),
    ),
    shortDesc = """Knocks out charged thermo""",
    longDesc = 
"""

""",
)
```
and the point of that `Sc` group is to "knock it out" by making the enthalpy very high, so I don't think it is an issue if this PR makes the thermo even higher

**Pull request merged**
