### PR TITLE
AECs and BACs

### PR DESCRIPTION
**Pull request by hwpang**

### CODE REVIEW

**Comment by oscarwumit** [comment]
Thanks for the PR, can you take a look at the failed test and rebase this PR with the main? Contents look good to me and let's get this merged.

**Comment by hwpang** [comment]
@JacksonBurns I see that the Conda Build test failed but this PR doesn't change anything related to that. Could you take a look?

**Comment by JacksonBurns** [comment]
Let me try and figure out why this failed real quick, otherwise agreed

**Comment by rwest** [comment]
Just wondering, how/where are these documented? For users to find out what is available and when it can be used? For example, @ssun30 thinks he might be able to use `'g42023'` for his work that uses g4, but we're not 100% confident what it is.
And the atom energies don't exactly match what he gets calculating an atom with `g4` in gaussian16. (which are [here](https://github.com/ReactionMechanismGenerator/RMG-database/commit/8e013fde2ce70f02209a579c821d54666a6f0231))

**Comment by hwpang** [comment]
@rwest Thanks for the question! These AECs/BACs are the results of this paper: https://pubs.acs.org/doi/full/10.1021/acs.jpca.4c00949 and all the calculation output files, the fitting scripts, and the fitting results can be found on the Zenodo: https://zenodo.org/records/8411688.

**Comment by rwest** [comment]
Great. Can I suggest we add metadata to the RMG-database, perhaps saying exactly what software settings to use, and maybe extend arkane documentation?  (apologies if this is a nonsense request)

Next question: if we want to use Arkane for species including Boron, how do we go about deriving AECs for Boron? (and BACs, or whatever). Maybe here's not the best place to ask. Su will reach out after he's read the paper :)

**Comment by hwpang** [comment]
@rwest Yes, I will work on adding the metadata and arkane documentation. Also, Su, please definitely reach out! I'm happy to help.

**Pull request merged**
