### PR TITLE
Merged all 2+2_cycloaddition families in to one 2+2_cycloaddition family

### PR DESCRIPTION
**Pull request by hwpang**
All 2+2_cycloaddition families can be represented using one tree..

1. Merged training and NIST reactions from all 2+2_cycloaddition families
2. Manually converted rules from all families to training reactions
3. Used ATG to generate new tree

### CODE REVIEW

**Review by mjohnson541 — COMMENTED** [review]
Thanks Hao-Wei! I need to see the RMG-tests results before I can approve it, but everything looks good so far! Can you rebase?

**Comment by hwpang** [comment]
@mjohnson541 Thanks for the review! I rebased and force-pushed. The github action test has been passed :)

**Comment by xiaoruiDong** [comment]
@hwpang All tests passed. Can you rebase again and let me know? I can help merge this PR

**Comment by hwpang** [comment]
@xiaoruiDong All checks have passed :)

**Comment by hwpang** [comment]
Rebased! Last rebase's github action test failed, which I suspect to be related to some recently merged changes to the RMG database test. Hopefully this rebase would pass the test.

**Comment by hwpang** [comment]
@xiaoruiDong Rebased and all tests passed!

**Comment by hwpang** [comment]
@mjohnson541 Rebased!

**Pull request merged**
