### PR TITLE
Forbid a charged carbene in singlet_carbene_intra_disproportionation

### PR DESCRIPTION
**Pull request by alongd**
This solves #213 by adding the simple forbidden group
```
1 *1 C u0 p1 c-1
```
to `carbene in singlet_carbene_intra_disproportionation`.

@zjburas and I were thinking what would be the best approach (adding `c0` to all node? leaving the forbidden group?) @nyee would you have any suggestions?

### CODE REVIEW

**Comment by alongd** [comment]
@nyee, thanks for your comment in #213.
I changed this PR to add `c0` to all carbenes instead of forbidding `c-1`.
Ready for review (once Travis is fixed, https://github.com/ReactionMechanismGenerator/RMG-Py/issues/1208)

**Comment by alongd** [comment]
@zjburas , I re-ran Travis, and this PR is now clean. Could you take a look?

**Comment by alongd** [comment]
Yes, it does the trick and solves #213 as well.

**Comment by zjburas** [comment]
Great, then I think someone with the authority can merge this.

**Comment by alongd** [comment]
@nyee, I still can't merge PRs on the database repo... strange.
Could you or anyone else with merging privileges please merge this?

**Comment by mliu49** [comment]
@alongd, I modified the permissions. You should be able to merge now.

**Comment by alongd** [comment]
Thanks @mliu49 !

**Pull request merged**
