### PR TITLE
Tree training co disproportionation

### PR DESCRIPTION
**Pull request by sevyharris**

### CODE REVIEW

**Comment by kspieks** [comment]
Hey @sevyharris. Thanks for this PR :) I checked out this branch and just tried re-fitting this tree. However, I get different values in `rules.py` than what is committed in this PR. Can you please re-run the ATG script to fit this family and verify if you get the same values?

**Comment by sevyharris** [comment]
Hey @kspieks, I refitted the family tree and got slightly different results. I committed the changes so you can check to see if those entries are closer to the ones you were getting.

**Comment by kspieks** [comment]
@sevyharris Thanks for refitting! Yes I match your latest values. Can you please rebase?

**Review by kspieks — APPROVED** [review]

**Comment by xiaoruiDong** [comment]
Thanks @sevyharris @kspiek. This PR will be merged after the tests.

**Pull request merged**
