### PR TITLE
Enable RMG to produce benzene through propargyl radical recombination

### PR DESCRIPTION
**Pull request by zjburas**
Consists of additions and changes to both the thermo and kinetics databases to enable RMG to produce benzene through the propargyl radical (C3H3) recombination pathway of Miller and Klippenstein (Miller, J. A.; Klippenstein, S. J., The Recombination of Propargyl Radicals and Other Reactions on a C6H6 Potential. J. Phys. Chem. A 2003, 107, 7783-7799.). This pathway has long been known to be the dominant route from small molecules (like those in natural gas) to the first aromatic ring, benzene. 

## Thermo:

1. Because two singlet carbenes are critical intermediates on the C3H3 recombination PES, it is important that their thermo be estimated accurately. Rather than create HBI corrections in radical.py for singlet carbenes (which currently are not accessed anyway, as pointed out in RMG-Py Issue #792 and PR #808), @nyee suggested creating a new branch in groups.py specifically for singlet carbenes. This branch consists of 9 entries with data, 7 of which were fit to the following singlet carbenes in the DFT_QCI_thermo library:

   - image
   - image
   - image
   - image
   - image
   - image
   - image

   The other 2 entries are the 2 critical intermediates on the C3H3+C3H3 surface, shown below, the thermo for which were re-calculated by @cfgold using the same methodology as in the DFT_QCI library:

   - image
   - image

   These changes should resolve RMG-Py Issue #792 and replace PR #808 (sorry @bslakman ).

2. 3 new triplet carbene HBI corrections were added to radical.py, using the following triplet carbenes in the DFT_QCI library to fit the corrections:
 
   - image
   - image
   - image

   These new corrections were added to eliminate the dependence of the triplet carbene HBI values on the singlet values, so that the next change could be implemented.

3. All singlet carbene HBI corrections removed from  radical.py to prevent confusion with new singlet carbene groups in group.py, and also because the HBI corrections are not being used for singlet  carbenes anyway. The only exception is the HBI correction for CH2, which is kept in because  it is used by non-carbenes like SiH2.

4. 2 new polycyclic thermo corrections were added to polycyclic.py. The first is for another critical intermediate on the C3H3+C3H3 PES:

   - image

   The second is for a strained bicycic that RMG would greatly over-predict otherwise:

   - image

   Initially, GAV estimates for enthalpy of formation were ~30 and ~70 kcal/mol too low, respectively. New groups were fit to M06 calculations of the above species using @KEHANG 's method.

## Kinetics

1. Created 8 new reaction families corresponding to the elementary steps on Miller's C3H3+C3H3 PES necessary to form benzene. They are:

   - **Singlet_Carbene_Intra_Disproportionation**

   image

   - **Intra_5_membered_conjugated_C=C_C=C_addition**

   image

   - **Intra_Diels_alder_monocyclic**

   image

      _Note:_ The existing family previously named Intra_Diels_alder  was more accurately and precisely renamed as Intra_Retro_Diels_alder_bicyclic to distinguish it from the above, new family.

   - **Concerted_Intra_Diels_alder_monocyclic_1,2_shiftH**

   image

   - **Intra_2+2_cycloaddition_Cd**

   image

   - **Intra_ene_reaction**

   image

      _Note:_ This family replaces the previous H_shift_cyclopentadiene family. All of the groups, rules and training rxns of the old family are retained, the new family is just more generalized. Also, this family is its own reverse.

   - **Cyclopentadiene_scission**

   image

   - **6_membered_central_C-C_shift**

   image

      _Note:_ This family is its own reverse.

2. At least 1 training reaction was added to each of the new families above using TST calculated k's on Miller's C3H3+C3H3 surface. For the 2 families that are their own reverse, training reactions were entered in both forward and reverse directions. A high-P kinetic library was also created with these k's.

3. Because the ratio of fulvene to benzene formed is an important observable on the C3H3+C3H3 PES, _all_ of the reactions in the existing  Fulvene_H kinetic library (based on Aaron's CBS-QB3 calculations) were added as training reactions. The reactions in this library describe H-catalyzed isomerization of fulvene to benzene, which becomes important at ~800 K. Previously, only about half of the library reactions had been turned into training reactions. Also, the product of one of the library reactions was mis-labeled, causing RMG to think that reaction has no family. This error was fixed in the library. 

## Miscellaneous
1. Singlet, but not triplet, carbenes were removed from the globally forbidden structures list.

2. There is a corresponding RMG-Py PR with the 2 following necessary changes:
   
   - Because many of the new reaction families use the GAIN_PAIR and LOSE_PAIR actions, in order for them to work the recently discovered bug in these actions needs to be fixed (RMG-Py PR #868).

   - The 2 new reaction families that are their own reverse are hardcoded in rmgpy/data/kinetics/family.py, where the switching of atom labels in reversing the reaction direction are defined.

Finally, the above changes were validated by comparing RMG's new predictions against the 1,5-hexadiyne pyrolysis experiments of Stein et al., as well as Miller's predictions. If only the 8 new reaction families are turned on during the RMG job, the agreement between the experiment and both predictions is good: 

image

However, if all of the default RMG families are turned on, in addition to the 8 new families, the RMG predictions deviate from both experiment and Miller at higher temperatures:

image

As mentioned earlier, this is because of the H-catalyzed isomerization of fulvene to benzene coming into play in RMG at higher T. In the RMG model, H atoms that are generated have nothing else to do other than convert fulvene to benzene. In Stein's experiment, however, there was likely some other H-atom sink (such as the walls or an impurity) that prevented H from converting fulvene to benzene indefinitely. Miller's predictions did not consider this process at all.

Nonetheless, the disagreement between RMG predictions and literature is  not caused by the changes in this PR, as demonstrated by the first plot above. It will be interesting in the future to see how general RMG predicts this pathway to be. For example, if one of the H's on C3H3 was replaced with a methyl group,  would a substituted benzene ring eventually form? This is something that has not been previously investigated to my knowledge,  although Miller does mention the possible extensibility of this pathway.

### CODE REVIEW

**Comment by mliu49** [comment]
There seems to be something odd going on with the Singlet_Carbene_Intra_Disproportionation family. In the models you sent me, there are a number of unbalanced reactions, where the reactant doesn't actually have a lone pair, and then the product magically loses 2 hydrogens.

Example 1: [Reactant](http://rmg.mit.edu/database/molecule/multiplicity%202%0A1%20%20C%20u0%20p0%20c0%20%7B2%2CS%7D%20%7B3%2CS%7D%20%7B11%2CS%7D%20%7B12%2CS%7D%0A2%20%20C%20u0%20p0%20c0%20%7B1%2CS%7D%20%7B5%2CS%7D%20%7B13%2CS%7D%20%7B14%2CS%7D%0A3%20%20C%20u0%20p0%20c0%20%7B1%2CS%7D%20%7B4%2CS%7D%20%7B15%2CS%7D%20%7B16%2CS%7D%0A4%20%20C%20u0%20p0%20c0%20%7B3%2CS%7D%20%7B5%2CB%7D%20%7B6%2CB%7D%0A5%20%20C%20u0%20p0%20c0%20%7B2%2CS%7D%20%7B4%2CB%7D%20%7B7%2CB%7D%0A6%20%20C%20u0%20p0%20c0%20%7B4%2CB%7D%20%7B8%2CB%7D%20%7B10%2CS%7D%0A7%20%20C%20u0%20p0%20c0%20%7B5%2CB%7D%20%7B9%2CB%7D%20%7B17%2CS%7D%0A8%20%20C%20u0%20p0%20c0%20%7B6%2CB%7D%20%7B9%2CB%7D%20%7B18%2CS%7D%0A9%20%20C%20u0%20p0%20c0%20%7B7%2CB%7D%20%7B8%2CB%7D%20%7B19%2CS%7D%0A10%20C%20u1%20p0%20c0%20%7B6%2CS%7D%20%7B20%2CS%7D%20%7B21%2CS%7D%0A11%20H%20u0%20p0%20c0%20%7B1%2CS%7D%0A12%20H%20u0%20p0%20c0%20%7B1%2CS%7D%0A13%20H%20u0%20p0%20c0%20%7B2%2CS%7D%0A14%20H%20u0%20p0%20c0%20%7B2%2CS%7D%0A15%20H%20u0%20p0%20c0%20%7B3%2CS%7D%0A16%20H%20u0%20p0%20c0%20%7B3%2CS%7D%0A17%20H%20u0%20p0%20c0%20%7B7%2CS%7D%0A18%20H%20u0%20p0%20c0%20%7B8%2CS%7D%0A19%20H%20u0%20p0%20c0%20%7B9%2CS%7D%0A20%20H%20u0%20p0%20c0%20%7B10%2CS%7D%0A21%20H%20u0%20p0%20c0%20%7B10%2CS%7D%0A) = [Product](http://rmg.mit.edu/database/molecule/multiplicity%202%0A1%20%20C%20u0%20p0%20c0%20%7B2%2CS%7D%20%7B5%2CS%7D%20%7B11%2CS%7D%20%7B12%2CS%7D%0A2%20%20C%20u0%20p0%20c0%20%7B1%2CS%7D%20%7B3%2CB%7D%20%7B6%2CB%7D%0A3%20%20C%20u0%20p0%20c0%20%7B2%2CB%7D%20%7B4%2CB%7D%20%7B7%2CS%7D%0A4%20%20C%20u0%20p0%20c0%20%7B3%2CB%7D%20%7B8%2CB%7D%20%7B10%2CS%7D%0A5%20%20C%20u0%20p0%20c0%20%7B1%2CS%7D%20%7B7%2CD%7D%20%7B13%2CS%7D%0A6%20%20C%20u0%20p0%20c0%20%7B2%2CB%7D%20%7B9%2CB%7D%20%7B14%2CS%7D%0A7%20%20C%20u0%20p0%20c0%20%7B3%2CS%7D%20%7B5%2CD%7D%20%7B16%2CS%7D%0A8%20%20C%20u0%20p0%20c0%20%7B4%2CB%7D%20%7B9%2CB%7D%20%7B17%2CS%7D%0A9%20%20C%20u0%20p0%20c0%20%7B6%2CB%7D%20%7B8%2CB%7D%20%7B15%2CS%7D%0A10%20C%20u1%20p0%20c0%20%7B4%2CS%7D%20%7B18%2CS%7D%20%7B19%2CS%7D%0A11%20H%20u0%20p0%20c0%20%7B1%2CS%7D%0A12%20H%20u0%20p0%20c0%20%7B1%2CS%7D%0A13%20H%20u0%20p0%20c0%20%7B5%2CS%7D%0A14%20H%20u0%20p0%20c0%20%7B6%2CS%7D%0A15%20H%20u0%20p0%20c0%20%7B9%2CS%7D%0A16%20H%20u0%20p0%20c0%20%7B7%2CS%7D%0A17%20H%20u0%20p0%20c0%20%7B8%2CS%7D%0A18%20H%20u0%20p0%20c0%20%7B10%2CS%7D%0A19%20H%20u0%20p0%20c0%20%7B10%2CS%7D%0A)

image image

Example 2: [Reactant](http://rmg.mit.edu/database/molecule/multiplicity%202%0A1%20%20C%20u0%20p0%20c0%20%7B2%2CS%7D%20%7B4%2CS%7D%20%7B13%2CS%7D%20%7B14%2CS%7D%0A2%20%20C%20u0%20p0%20c0%20%7B1%2CS%7D%20%7B7%2CS%7D%20%7B11%2CS%7D%20%7B12%2CS%7D%0A3%20%20C%20u0%20p0%20c0%20%7B5%2CS%7D%20%7B15%2CS%7D%20%7B16%2CS%7D%20%7B17%2CS%7D%0A4%20%20C%20u0%20p0%20c0%20%7B1%2CS%7D%20%7B5%2CB%7D%20%7B6%2CB%7D%0A5%20%20C%20u0%20p0%20c0%20%7B3%2CS%7D%20%7B4%2CB%7D%20%7B8%2CB%7D%0A6%20%20C%20u0%20p0%20c0%20%7B4%2CB%7D%20%7B7%2CS%7D%20%7B9%2CB%7D%0A7%20%20C%20u1%20p0%20c0%20%7B2%2CS%7D%20%7B6%2CS%7D%20%7B18%2CS%7D%0A8%20%20C%20u0%20p0%20c0%20%7B5%2CB%7D%20%7B10%2CB%7D%20%7B20%2CS%7D%0A9%20%20C%20u0%20p0%20c0%20%7B6%2CB%7D%20%7B10%2CB%7D%20%7B19%2CS%7D%0A10%20C%20u0%20p0%20c0%20%7B8%2CB%7D%20%7B9%2CB%7D%20%7B21%2CS%7D%0A11%20H%20u0%20p0%20c0%20%7B2%2CS%7D%0A12%20H%20u0%20p0%20c0%20%7B2%2CS%7D%0A13%20H%20u0%20p0%20c0%20%7B1%2CS%7D%0A14%20H%20u0%20p0%20c0%20%7B1%2CS%7D%0A15%20H%20u0%20p0%20c0%20%7B3%2CS%7D%0A16%20H%20u0%20p0%20c0%20%7B3%2CS%7D%0A17%20H%20u0%20p0%20c0%20%7B3%2CS%7D%0A18%20H%20u0%20p0%20c0%20%7B7%2CS%7D%0A19%20H%20u0%20p0%20c0%20%7B9%2CS%7D%0A20%20H%20u0%20p0%20c0%20%7B8%2CS%7D%0A21%20H%20u0%20p0%20c0%20%7B10%2CS%7D%0A) = [Product](http://rmg.mit.edu/database/molecule/multiplicity%202%0A1%20%20C%20u0%20p0%20c0%20%7B2%2CS%7D%20%7B11%2CS%7D%20%7B12%2CS%7D%20%7B13%2CS%7D%0A2%20%20C%20u0%20p0%20c0%20%7B1%2CS%7D%20%7B3%2CB%7D%20%7B5%2CB%7D%0A3%20%20C%20u0%20p0%20c0%20%7B2%2CB%7D%20%7B4%2CB%7D%20%7B8%2CS%7D%0A4%20%20C%20u0%20p0%20c0%20%7B3%2CB%7D%20%7B6%2CB%7D%20%7B7%2CS%7D%0A5%20%20C%20u0%20p0%20c0%20%7B2%2CB%7D%20%7B9%2CB%7D%20%7B19%2CS%7D%0A6%20%20C%20u0%20p0%20c0%20%7B4%2CB%7D%20%7B9%2CB%7D%20%7B14%2CS%7D%0A7%20%20C%20u0%20p0%20c0%20%7B4%2CS%7D%20%7B10%2CD%7D%20%7B15%2CS%7D%0A8%20%20C%20u1%20p0%20c0%20%7B3%2CS%7D%20%7B10%2CS%7D%20%7B17%2CS%7D%0A9%20%20C%20u0%20p0%20c0%20%7B5%2CB%7D%20%7B6%2CB%7D%20%7B16%2CS%7D%0A10%20C%20u0%20p0%20c0%20%7B7%2CD%7D%20%7B8%2CS%7D%20%7B18%2CS%7D%0A11%20H%20u0%20p0%20c0%20%7B1%2CS%7D%0A12%20H%20u0%20p0%20c0%20%7B1%2CS%7D%0A13%20H%20u0%20p0%20c0%20%7B1%2CS%7D%0A14%20H%20u0%20p0%20c0%20%7B6%2CS%7D%0A15%20H%20u0%20p0%20c0%20%7B7%2CS%7D%0A16%20H%20u0%20p0%20c0%20%7B9%2CS%7D%0A17%20H%20u0%20p0%20c0%20%7B8%2CS%7D%0A18%20H%20u0%20p0%20c0%20%7B10%2CS%7D%0A19%20H%20u0%20p0%20c0%20%7B5%2CS%7D%0A)

image image

**Comment by zjburas** [comment]
Good catch. I guess there are two general explanations:

1. The Singlet_Carbene_Intra_Disproportionation family is being improperly used somehow to convert a saturated single bond into a double bond.

2. The "p1" in the adjacency list is lost somewhere in the process of writing  the species dictionary.

Regarding 1, I ran generate_reactions on the first example reactant above (no lone pairs) and Singlet_Carbene_Intra_Disproportionation didn't do anything unexpected (i.e., it didn't do the problematic reaction above). 

This makes me lean towards 2, but it's also weird because "p1" does show up in the adjacency lists of several species in the species_dictionary.  So I don't know what would be special about the species you found that would cause their "p1"'s  to be lost. Maybe it has to do with their resonance?

**Comment by mliu49** [comment]
Thanks for the ideas! It is in fact an issue with resonance structure generation. Currently, RMG uses RDKit for kekulization, and RDKit uses implicit H atoms. Basically, the lone pairs are being lost during the conversion process, and get turned into H's on the way back to an RMG molecule.

It seems that normally, RMG will convert a lone pair into two unpaired electrons, but it requires that the entire molecule have multiplicity=1 ([see here](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/molecule/generator.py#L335)).

However, this problem will also be circumvented by changes that I'm working on, which include a new first-party kekulization module. If you want to cherry-pick the relevant commits as a temporary measure, they are on my [reactBenzene](https://github.com/mliu49/RMG-Py/commits/reactBenzene) branch, commits f21751fd and 36365b3d.

**Comment by zjburas** [comment]
Replaced by PR #205

**Pull request closed without merging**
