### PR TITLE
github actions CI maintainence

### PR DESCRIPTION
**Pull request by JacksonBurns**
- copy the download logic from RMG-Py (https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2669) that updates the version of download-artifact
 - increment setup-miniconda

Pair PR with https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2669

### CODE REVIEW

**Comment by JacksonBurns** [comment]
@rwest I tacked on a85e44c to fix the Conda build check when running from forks.

**Review by rwest — APPROVED** [review]
The point of the conda_build change is so that the the workflow, on forks, does not fail (but it won't actually upload binaries), correct?
I can't tell that it'll work by reading the diff, but if it does what you intended, then this all looks fine to me.

**Comment by JacksonBurns** [comment]
Yeah it just runs the build but does not publish it

**Comment by jonwzheng** [comment]
It looks like there's potentially something broken with this as CI is failing for new PRs:

```
Run actions/download-artifact@v4
Downloading single artifact
Error: Unable to download artifact(s): Artifact not found for name: stable_regression_results
        Please ensure that your artifact is not expired and the artifact was uploaded using a compatible version of toolkit/upload-artifact.
        For more information, visit the GitHub Artifacts FAQ: https://github.com/actions/toolkit/blob/main/packages/artifact/docs/faq.md
```

**Comment by JacksonBurns** [comment]
The name of the GitHub actions token was being passed incorrectly, I copied the fix in from the RMG-Py PR which fixed it.

**Pull request merged**
